### ISSUE TITLE
not possible to add an article to a collection when in facsimile view

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#1000]
..to do this, one needs to switch back to transcript view at the moment, e.g. https://impresso-project.ch/app/issue/LLE-2005-03-10-a/page/LLE-2005-03-10-a-p0032/article/LLE-2005-03-10-a-i0347 

@PaulSchroeder will work on integrating the "add to collection" button to the currently existing button bar

**Comment by PaulSchroeder** [comment]
I tried to address this simple issue, then I realised that in the current dev, we have a brand new viewer (with it's own set of issues) so I reworked the header component, this is how it looks now on dev :

<img width="1044" alt="Screenshot 2020-09-10 at 17 51 11" src="https://user-images.githubusercontent.com/32929425/92758643-3a2b2380-f38f-11ea-9e0c-f94941017645.png">

**Comment by danieleguido** [comment]
Tested, it's working on dev
