### ISSUE TITLE
Collections do not always display item count

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#1003]
Example from my collections:

![grafik](https://user-images.githubusercontent.com/4408050/92880917-c3ce0600-f40e-11ea-8239-a83413c368fc.png)

**Comment by PaulSchroeder** [comment]
this is a known issue ...
when I create a collection from search results, `collection.countItems` is set correctly,
however when adding or removing items manually to a collection, this field is not updated.

I guess it has to do with collection indexing ... @danieleguido ?
