### ISSUE TITLE
Common error: “TypeError: n.issue is undefined”

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#1024]
Common error: “TypeError: n.issue is undefined”, example: https://impresso-project.ch/app/issue/luxwort-1923-03-17-a/page/luxwort-1923-03-17-a-p0003/article/luxwort-1923-03-17-a-i0031

**Comment by danieleguido** [comment]
it is acttually working on our preprod https://dev.impresso-project.ch/app/issue/luxwort-1923-03-17-a/page/luxwort-1923-03-17-a-p0003/article/luxwort-1923-03-17-a-i0031
