### ISSUE TITLE
Viewer: Page count off when switching from facsimile to transcript

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#1031]
article: https://dev.impresso-project.ch/app/issue/JDG-1979-09-15-a/view?p=15&articleId=i0064

when switwching from "facsimile" to "transcript" the wrong page is displayed. Strangely, when I find the correct one and redo the switch it works fine

**Comment by mduering** [comment]
Indeed that was the problem but could not reproduce now

**Comment by danieleguido** [comment]
view component has been updated since July, closing for now
