### ISSUE TITLE
Update needed: Home page

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#1047]
NOTE: For some gifs, videos we need to wait for the new data to arrive. Other things can be done right away.

- [ ] @danieleguido any chance to have videos play as overlays on the home page to make it more convenient than switching tabs?
- [ ] Design question can we add sth like: "Take a moment to familiarise yourself with impresso's advanced search and exploration workflows" - so as to entice visitors to scroll down and check challenges and gifs?

- [ ] impresso data rundown needs update when new data is available
- [x] remove "LInes off" and "Dark mode"
- [ ] add link to mailing list in contact segment

Reconstruct...

- [ ] animated gif still shows old search.
- [ ] new version of gif could be zoomed in on the search pill to allow reading and can then replace the video
- [x] Old title: Reconstruct the coverage of the composer Robert Schumann 
Suggested new title: Search for the composer Robert Schumann

- [x] Perform this Query runs a search for "Robert Schumann" not for the linked entity
- [ ] Video seems a bit redundant now, remove

Find performances..

- [x] search with music topic broken
- [ ] new version of gif could be zoomed in on the left filter pane to allow reading and can then replace the video

Collections..

- [ ] update video
- [x] Rephrase
OLD: Collections are curated lists of articles
NEW: Collections are curated lists of articles which can e.g. be searched, compared and exported.

Horoscopes

- [x] query is broken

- [ ] update video

Date range

- [x] query is broken
- [ ] https://vimeo.com/364796757 - does not play
- [ ] video redundant, can be replaced by zoomed in gif? 

Merge collections

- [x] video does not display
- [ ] likely needs update as well

Front page

- [ ] again a more zoomed in gif here?

 
Curate result list

- [x] video does not play
- [ ] likely needs update

**Comment by danieleguido** [comment]
see #1168
