### ISSUE TITLE
I&C: small bugs

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#1072]
- [x] in date distribution view, mouseover says "o results / 1 result / 0 results"  when "%" is selected
- [x] for 1792 we have a peak but 0 results?
![Screenshot from 2022-02-25 17-23-52](https://user-images.githubusercontent.com/4408050/155750650-e0b42bf9-33de-4b32-9df2-34bdbc3cb845.png)
https://dev.impresso-project.ch/app/compare?left=CgIYAgoQEAIYByABKghyb2RlbWFjaw%3D%3D&right=ChIIARACGAcgASoIY2F0dGVub20%3D

**Comment by danieleguido** [comment]
There's 1 result for 1792 it seems: 
![Screenshot 2022-05-06 at 11 14 16](https://user-images.githubusercontent.com/1181642/167103440-dec9c3f0-f957-4013-a570-8bcd50724192.png)
