### ISSUE TITLE
Collections: Can't create new collection

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#1073]
Entered a name, "Create Collection" button stays grey

**Comment by danieleguido** [comment]
On it! not sure it was working before :D .. For the moment you can create new collections from the search
<img width="554" alt="Screenshot 2022-03-01 at 11 55 28" src="https://user-images.githubusercontent.com/1181642/156156534-6b7194fc-2ce2-4c9f-a2c6-9137b7d5a0ba.png">

**Comment by mduering** [comment]
still needs to be sorted out - either make it work or hide option
