### ISSUE TITLE
Recommendations: Error

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#1074]
{ "route": [ "articles-recommendations", "create" ], "message": "request to https://dev.impresso-project.ch/recsys/recommend/ failed, reason: unable to verify the first certificate", "code": "UNABLE_TO_VERIFY_LEAF_SIGNATURE", "name": "Error" } paths.articles-recommendations.create

https://dev.impresso-project.ch/app/collections/local-duma-ExQ01pUa?tab=recommendations

**Comment by danieleguido** [comment]
it was due to a misconfiguration in the config file, now it's working :)
