### ISSUE TITLE
Search: Date filter update through mouse selection does not work

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#1078]
Selecting a date period in the graph does not create a new filter
Selection gets reset after clicking on "Add new date filter"

**Comment by danieleguido** [comment]
Fixed as it is now not possible to select by brush :) 

<img width="394" alt="Screenshot 2024-09-25 at 12 08 23" src="https://github.com/user-attachments/assets/0a70fd10-192b-495a-b7b3-45cad8bbfc37">
