### ISSUE TITLE
user registration - hyperlinks broken/missing in auto-reply email

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#1108]
This [short video](x-webdoc://EA12B4AD-14CE-487A-9F14-B9F2E244DBE7) gives an overview of the impresso project and its ambitions while the impresso Challenges offer a step-by-step guide with advanced exploratory workflows around which the interface was designed. You can follow a guided tour of the interface in a series of YouTube videos.

Researching digitised newspapers 
Our lesson on the Ranke2 learning platform gives a first overview of the peculiarities of digitised newspapers as historical sources. Our tutorial on the PARTHENOS platform discusses the challenges and opportunities researchers face when dealing with semantically enriched, digitised newspapers.

If you encounter any difficulty, do not hesitate to visit the FAQ page or to get in touch with us, either via email or via the chat box on the interface (black envelope)

Where can I edit this?

**Comment by danieleguido** [comment]
which link is broken @mduering ? in which template ? Email templates are here, in txt and html https://github.com/impresso/impresso-user-admin/tree/develop/impresso/templates/emails
