### ISSUE TITLE
Date filters in TR Netlify

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#1150]
![image](https://user-images.githubusercontent.com/4408050/219660183-9c7929bb-85da-4641-b8d5-86b9c2af698e.png)

Entered 1.1.1910 and 1.1.1970 

https://impresso-project.netlify.app/text-reuse/?p=1&sq=CjQIARACGAoqLDE5MTAtMDEtMDFUMDA6MDA6MDBaIFRPIDE5NzAtMDEtMDFUMjM6NTk6NTla

**Comment by mduering** [comment]
Passages count is off as well

**Comment by danieleguido** [comment]
Date Filter has been updated in #1188 
<img width="385" alt="Screenshot 2024-03-18 at 15 04 46" src="https://github.com/impresso/impresso-frontend/assets/1181642/4faa167f-e15d-45bb-a0ed-4f0b62e95459">
