### ISSUE TITLE
[text reuse v2] refine translation label for dynamic range tooltips

### ISSUE THREAD

**Issue by danieleguido** [impresso/impresso-frontend#1157]
- renaming "Day Delta" to "Time Span in Days" Mouseover: from "range: 22-125" to: "Time span: 22-125 days"
- A small suggestion for more clarity: instead of "value: 5" could the mouseover read "cluster size: 5"

**Comment by mromanello** [comment]
@danieleguido I'm closing this as it seems fixed (to me) but feel free to reopen it.
