### ISSUE TITLE
[text reuse v2] Not able to set manually the time span filter

### ISSUE THREAD

**Issue by mromanello** [impresso/impresso-frontend#1159]
two small issues here:
- [ ] when changing the values to e.g. 0-365 and then clicking on the button nothing happens
- [ ] label button says `actions.applyfilter` but should be renamed for consistency with rest of the app
<img width="425" alt="Screenshot 2023-04-20 at 11 27 56" src="https://user-images.githubusercontent.com/310693/233323657-db3a74f8-4cdb-40ba-a97e-cc44e48b796d.png">

**Comment by danieleguido** [comment]
Fixed in current prod :)
<img width="1000" alt="Screenshot 2024-03-18 at 15 03 19" src="https://github.com/impresso/impresso-frontend/assets/1181642/1e34368a-d683-4c5a-9a09-fd28f8366d0d">
