### ISSUE TITLE
impresso public API does not retrieve data for dev collections

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#1162]
Example:

r2 = requests.get(f'{API_BASE_URL}/articles', params={
    'filters': json.dumps([
      {"type":"hasTextContents"},
      {"type":"collection","q":["local-duma-1uHFPm12"]}
    ])
})
res2 = r2.json()
print(r2.url)
display(Markdown(f'*n. articles available for user prefix `local-duma` OR `local-eb`*: **`{res2["total"]}`**'))

**Comment by danieleguido** [comment]
Close it for now, see new development to impresso-middle-layer
