### ISSUE TITLE
Article coordinates are off and look strange in Search snippet view

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#1197]
![image](https://github.com/impresso/impresso-frontend/assets/4408050/f925d4e5-6d7d-4ad4-a518-ef098d5c8c87)

**Comment by danieleguido** [comment]
url?

**Comment by danieleguido** [comment]
See http://localhost:8080/app/search?sq=CgIYAgoJEAIYCSoDRlpHCjIQAhgKKiwyMDA1LTA0LTAyVDAwOjAwOjAwWiBUTyAyMDA1LTA0LTAyVDIzOjU5OjU5WgoLEAIYByABKgNBUkQ%3D&p=1
