### ISSUE TITLE
Text reuse: Link to article from left side of passage comparison leads to front page only, ride side works ok

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#1205]
Example: 
link in passages comparison:
https://dev.impresso-project.ch/app/issue/GDL-1984-06-25-a/view?p=1&articleId=i0136 

gets resolved to:
https://dev.impresso-project.ch/app/issue/EXP-1984-02-27-a/view?p=1&articleId=i0215

actually expected page:
https://dev.impresso-project.ch/app/issue/EXP-1984-02-27-a/view?p=13&articleId=i0215

**Comment by danieleguido** [comment]
Hi @mduering maybe it's just the page which is wrong: is this link correct? 
https://dev.impresso-project.ch/app/issue/GDL-1984-06-25-a/view?p=18&articleId=i0136

**Comment by danieleguido** [comment]
it looks like pqge is not shipped from the websockets request. todo in IML

**Comment by danieleguido** [comment]
Fixed in develop :)
