### ISSUE TITLE
Share article shows strange detailed time instead of a simple publication date

### ISSUE THREAD

**Issue by simon-clematide** [impresso/impresso-frontend#1206]
<img width="549" alt="image" src="https://github.com/impresso/impresso-frontend/assets/3041168/b0624090-7e91-4a8d-b864-18d197325a42">

 (00:29:46 seems entirely random to me)
https://impresso-project.ch/app/search?sq=CgIYAgoQEAIYFyoKT3BlblB1YmxpYwoJEAIYCSoDRFZG

**Comment by danieleguido** [comment]
This is already fixed in the upcoming release, see dev version
