### ISSUE TITLE
Bad display of General Error / network related errors

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#1226]
https://impresso-project.ch/app/search/ngrams?sq=CgQIARgC&unigrams=fukushima,chernobyl,tschernobyl

{ "route": [ "search", "find" ], "message": "ResourceRequest timed out", "code": 500, "name": "GeneralError" } paths.search.find
{ "route": [ "ngram-trends", "create" ], "message": "server error", "code": 500, "name": "GeneralError" } paths.ngram-trends.create

**Comment by danieleguido** [comment]
General Error like this one are bad but temporary issues, just ref to our slack channel :) 
I've renamed the issue to take into account the bad display of the error messge

**Comment by danieleguido** [comment]
in develop there is a plain display of GeneralError (and now everything is much faster). To be tested properly
