### ISSUE TITLE
Article view in text mode does not jump to article

### ISSUE THREAD

**Issue by simon-clematide** [impresso/impresso-frontend#124]
When pressing the view button in the result list, I expect the viewer (in Text mode) to jump to the article of interest.

![image](https://user-images.githubusercontent.com/3041168/49952964-65a08600-fefd-11e8-9afa-d07a37fdcbcc.png)

However, this only happens in Image mode. In Text mode, I end up at the beginning of the page (I suspect):
![image](https://user-images.githubusercontent.com/3041168/49953054-95e82480-fefd-11e8-9e36-230dc8d915d7.png)

I would expect to end up here:
![image](https://user-images.githubusercontent.com/3041168/49953148-c29c3c00-fefd-11e8-805c-b6b9a2635086.png)

**Comment by danieleguido** [comment]
Fixed in current release
