### ISSUE TITLE
Blue hover color in article mode conflicts with blue selection color and is misleading

### ISSUE THREAD

**Issue by simon-clematide** [impresso/impresso-frontend#125]
The blue hover color conflicts with the selection color of a search article. When you load a large page and have the mouse in the middle of the page, you might think that the article with the mouse on it is the selected article, (especially if the real article is not visibe in the viewport). I think the hover coloring scheme must be different from the article selection color.
The screen shot illustrates how the left article of <https://impresso-project.ch/dev/#/issue/GDL-1902-05-12-a/page/GDL-1902-05-12-a-p0002/article/GDL-1902-05-12-a-i0013> is highlighted by mouse over whereas the real article would be the one on  the right.

![image](https://user-images.githubusercontent.com/3041168/50183216-b0613a00-0311-11e9-94de-5b33439fb7c2.png)

**Comment by simon-clematide** [comment]
@danieleguido @PaulSchroeder 
There is another thing that bothers me when I actually try to closely read an article in article view from the facsimile. The blue color on the facsimile makes it very hard to read the content. 
At the risk of repeating myself, I think the article view should enable a distraction free reading/viewing of the article I am actually interested in.

![image](https://user-images.githubusercontent.com/3041168/54266060-ead81d00-4576-11e9-9dd6-87a5c2695680.png)

**Comment by danieleguido** [comment]
closed, added color in multiply mode
