### ISSUE TITLE
Topic filter: pb with "NOT containing" setting

### ISSUE THREAD

**Issue by e-maud** [impresso/impresso-frontend#1258]
On DEV, applying a negative topic filter search systematically give "Sorry, no articles found", even on known queries / demo paths.

Fro example:
- keyword search: arnhem -->  4,081 articles found containing arnhem 
- additional variants: amhem, arnheim, arnehm --> 6,843 articles found
- topic negative filter on 3 "sports" topics --> "Sorry, no articles found", whereas there should be.

![image](https://github.com/user-attachments/assets/90f3ad29-aec1-45ac-aef9-98545c6bd5e6)

**Comment by theorm** [comment]
A similar NOT search query:
 * does not work in `dev`: https://dev.impresso-project.ch/app/search?sq=CgIYAgoJEAIYCSoDU0daCh4IAhACGBIqFnRtLWRlLWFsbC12Mi4wX3RwMjNfZGU%3D&p=1
 * works in `prod`: https://impresso-project.ch/app/search?sq=CgIYAgoJEAIYCSoDU0daCh4IAhACGBIqFnRtLWRlLWFsbC12Mi4wX3RwMjNfZGU%3D&p=1
