### ISSUE TITLE
Inspect and compare: Error

### ISSUE THREAD

**Issue by theorm** [impresso/impresso-frontend#1262]
Getting an error when visiting [this page](https://dev.impresso-project.ch/app/compare?right=CgIYAgoOEAIYByABKgZtYWlzb24KChgVKgEwKgM2NDQKCBACGBYqAkxVCiAQAhgQKhphaWRhLTAwMDEtNTAtSmVhbl9GbGFtbWFuZwoOEAIYCSoIaW5kZXBsdXgKHggBEAIYEioWdG0tZnItYWxsLXYyLjBfdHAyMl9mcg==&left=ChAIARACGAcgASoGbWFpc29u):

```
{ "route": [], "message": "server error", "code": 500, "name": "GeneralError" }
```

**Comment by danieleguido** [comment]
It looks fixed, I don't get the error anymore 👍
