### ISSUE TITLE
add /topic page

### ISSUE THREAD

**Issue by danieleguido** [impresso/impresso-frontend#127]
- [x] display list of words and basic info
- [x] display list of words as a simple word cloud
- [x] display list of topic in the left column
- [x] add searh capabilities in the left column

**Comment by danieleguido** [comment]
@PaulSchroeder check the branch `feature/topic_page` :)
to be reviewed with @tvanbeek

**Comment by Bunoute** [comment]
![image](https://user-images.githubusercontent.com/32094266/52466078-53e80180-2b81-11e9-8bf8-031ca22b376d.png)
 when changing the "size by" option on the homepage of the TM visualisation, from "degree" to "highest word probability" it shifts a bit...
