### ISSUE TITLE
Article view / entity modal dialogue broken

### ISSUE THREAD

**Issue by e-maud** [impresso/impresso-frontend#1275]
In DEV, in the article view, the modal dialogue on entity seems not working:

<img width="639" alt="image" src="https://github.com/user-attachments/assets/d20696c3-0d0a-4a73-8996-ecd6c1c86440">

**Comment by theorm** [comment]
@e-maud do you have a link to this particular page?

**Comment by theorm** [comment]
Nevermind, I found it. Any entity on the search results page can be used to reproduce it.
