### ISSUE TITLE
Text reuse page: compare text reuse passages pop-up box not displaying buttons to jump

### ISSUE THREAD

**Issue by itsarturito** [impresso/impresso-frontend#1281]
When you click on compare with other passages in cluster, the buttons to jump between articles are not displayed and therefore not usable.

URL : https://dev.impresso-project.ch/app/text-reuse/passages?p=1&sq=ChIIARACGAcgASoIc2NhbmRhbGUKChgbKgI3MCoCOTk=&vis=trnewspapers_vs_newspapers&sort=-clusterSize

Screenshot dev app:
<img width="884" alt="Screenshot 2024-09-26 at 17 06 06" src="https://github.com/user-attachments/assets/4396c21f-4596-4ec7-9b84-89ebbaae9c66">

Screenshot production app:
![Screenshot 2024-09-26 at 17 06 30](https://github.com/user-attachments/assets/340df70c-a7b5-49ac-b977-76541f779eb0)

**Comment by theorm** [comment]
I believe the dropdown [has been removed](https://github.com/impresso/impresso-frontend/commit/09be136dfea664ca8ead9293df6bea7c6d0d71bb#diff-2e443c80d0d52813f36d99e285fd16608da36838fd6786d2a606ea3684a431b6L6) by @danieleguido.
