### ISSUE TITLE
Share widget not working as expected on dev

### ISSUE THREAD

**Issue by danieleguido** [impresso/impresso-frontend#1294]
Use https://dev.impresso-project.ch/app/search?sq=CgIYAgoOEAIYByABKgZvaXNlYXUKDxACGAcgASoHbWF1dmFpcwoQEAIYFyoKT3BlblB1YmxpYw%3D%3D&p=1

then click on "share", the iframe link contains "undefined" so it is probably just a config mistake

**Comment by theorm** [comment]
Fixed `undefined`, but the URL must still be misconfigured in `nginx.conf`. Need to have a look.

**Comment by theorm** [comment]
Fixed. See https://dev.impresso-project.ch/app/search?sq=CgIYAgoOEAIYByABKgZvaXNlYXUKDxACGAcgASoHbWF1dmFpcwoQEAIYFyoKT3BlblB1YmxpYw%3D%3D&p=1

Requires the following block placed before `/app` block in nginx.conf:

```
    location /app/widget {
        alias /opt/impresso-frontend/widget;
    }
```
