### ISSUE TITLE
`search`: clean facets look and feel

### ISSUE THREAD

**Issue by danieleguido** [impresso/impresso-frontend#131]
Clean facets layout:

- [ ] reducing font size and smallcaps the labels;
- [x] add the relevant informations in the facet items;
- [x]  use the correct number format according to the language; 
- [x] add the "reset" button only when a facet has been selected;
- [x] the search / clear buttons should appear only when we actually do something with the filter.

**Comment by simon-clematide** [comment]
I would expect the reset filter to appear (in read) next to the other filtering boxes right on the same line as 
![image](https://user-images.githubusercontent.com/3041168/83726317-a6d1ac00-a643-11ea-
84a6-60039bf00c9b.png)

**Comment by PaulSchroeder** [comment]
please also check PR #936 for searchbar suggestions
