### ISSUE TITLE
finalize collection page

### ISSUE THREAD

**Issue by tvanbeek** [impresso/impresso-frontend#137]

**Comment by Bunoute** [comment]
it seems I cannot add more than 10 articles to a collection.,.. not even the 12 selected on the search results...

**Comment by danieleguido** [comment]
a few things to do:
- [ ] homepage is still blank ? cfr method find of `collectable-items` service
- [ ] get rid of the two tab headers: my searches and my labels
- [ ] restyle left column header  to match other pages (leave the tabs)
- [ ] restyle left column to match other pages: no small-caps, left aligned
- [ ] add link to search page (prefilter by colleciton uid, ask @danieleguido)
