### ISSUE TITLE
Add feedback button website (LWI)

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#144]
An idea from Lars to ensure a steady flow of feedback as soon as the interface goes live:

They had a very good experience with the Feedback button on cvce.eu. The idea would be to place it visibly on the interface so that users have a low threshold to report problems, irritation, confusion etc. back to us as soon as the interface is launched. Ideally it connects directly to the Github Issues as well. 
What do you think?

We could combine this with a dedicated email feedback@impresso-project.ch

**Comment by tvanbeek** [comment]
integrated [tawk.to](http://tawk.to)
