### ISSUE TITLE
`search` page: verify multiple parallel calls to collection.find service

### ISSUE THREAD

**Issue by danieleguido** [impresso/impresso-frontend#233]
The IML receives 12 calls to collection.find service, is it somehow related to collection widget?

**Comment by PaulSchroeder** [comment]
yes, I guess it’s the `<add-to-collection>` component. I’ll look into it.

**Comment by PaulSchroeder** [comment]
please check my pull.
https://github.com/impresso/impresso-frontend/pull/234

**Comment by danieleguido** [comment]
Hi Paul, added comments to your PR :)
