### ISSUE TITLE
Feedback from Alpha Release (March 2019)

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#254]

**Comment by Bunoute** [comment]
on the date range: it should not be possible to have impossible date ranges, such as 1982-1950 :)
![image](https://user-images.githubusercontent.com/32094266/53965633-db2d8400-40f1-11e9-82d8-20d08ef59270.png)

Else, it is working great, many many thanks!

**Comment by Bunoute** [comment]
on the metadata (genealogy of newspaper titles): not only in GdL/JdL, also l'impartial/l'express
>> maybe we can add it to the "know issues"?

**Comment by mduering** [comment]
- [ ] **items on the y-axis in the term frequency chart do not scale up/down**

Frederic Clavert:

Hi all. Here is my first remark on the interface. I wanted to see traces of memory of the battle of Verdun. "memory" means in that case that i search for the term "Verdun", and then limit my search chronologically from the 12th of November 1918 to today.
What I want to see is if there is a memory of this battle in french-speaking swiss newspapers.
Problem is that if I look at the graph with the occurrences of the word 'Verdun', I cannot see if the word "Verdun" is used regularly (more or less each year around February or each ten years around the sixth year of the decade) because the ordinate stays too high because it is calculated in reference to the highest frequence of the word "Verdun" which is 1916. Am I clear?

![image](https://user-images.githubusercontent.com/4408050/54015075-e7135780-417e-11e9-91d1-d962e3071d14.png)

**Comment by Bunoute** [comment]
on search options: from Zoé K: need the "NEAR" search option

**Comment by mduering** [comment]
via Lars:

- [ ] allow start and end date to be identical to search for articles on a given day only (now leads to reset of the date range)
- [ ] include the end date in the query: If I search for 1.1.1950 as start and 2.1.1950 as end date, I only get articles from 1.1.1950

**Comment by mduering** [comment]
via Lars:

When in image viewer: 

- [ ] It is very hard to drag the page up and down. If I click somewhere to move the image and release, I am sent to whichever article I just clicked on. The only option is to find space which has not been OLRed which is hard.

**Comment by Bunoute** [comment]
Comfort remark: On the reading page: display as image: if i want to read the article as an image, I would prefer to be able to de-select the beautiful and very useful blue frame to the article. But when I click on it, I go to the text view and if I click elsewhere, it takes me to whatever article I clicked.
So, there should be only reading in the text view? (it is not a problem :)

**Comment by danieleguido** [comment]
@Bunoute @simon-clematide @mduering for region overlays in image viewer, ref to issue #100

**Comment by simon-clematide** [comment]
> via Lars:
> 
> When in image viewer:
> 
> * [ ]  It is very hard to drag the page up and down. If I click somewhere to move the image and release, I am sent to whichever article I just clicked on. The only option is to find space which has not been OLRed which is hard.

Same problem here. And when Martin Volk tried to move the things around. No scroll bars, and the default action for scrolling for normal macos users (not designer though) is zooming not scrolling.

**Comment by simon-clematide** [comment]
Being able to look at the texts of NZZ would be really nice.

**Comment by Bunoute** [comment]
From Theophile Naito:
Dear all,

Here are my remarks about this feature (librarian point of view!). Order isn't important.

It's a great feature.
What does "empty" mean (see Screen1.jpg)?
It seems to me that the information "empty"/"corrupted" (Screen1) may be important for administrators but not for users.
This block (Screen1) could also indicate the number of issues and not only the number of pages.
The block corresponding to some newspaper title could indicate the total number of pages and the number of issues for this newspaper (Screen2).
I am not sure that it's useful to display the two blocks together (Screen2). Especially if there isn't any data to compare (number of pages for example).
The text (Screen3) could simply be something like "50'704 issues".
The thumbnails should be clickable (Screen3).
The two blocks aren't vertically aligned after a search has been performed in the list of titles (Screen4).
A priori, it's not possible to know which horizontal line is corresponding to which newspaper (Screen5). It would be great to have the title somewhere on the line.
The lines corresponding to the newspapers are too close to each other (Screen5). It's my understanding that the total list of titles will anyway be too long to be display on a screen. I suggest to double the space between lines.
It would be great if it would be possible to display only the titles which have a "common history" (for example: Gazette de Lausanne, Journal de Genève and Le temps).
Even better would be to have this history visible on the lines corresponding to the newspaper. For example, the line corresponding to Gazette de Lausanne would merge with the line corresponding to Journal de Genève to give rise to the line corresponding to Le temps.
![Screen5](https://user-images.githubusercontent.com/32094266/55056209-d8291200-5065-11e9-82a3-9dbb4ec2b846.JPG)
![Screen4](https://user-images.githubusercontent.com/32094266/55056210-d8c1a880-5065-11e9-950f-6c2529c3505e.jpg)
![Screen1](https://user-images.githubusercontent.com/32094266/55056211-d8c1a880-5065-11e9-9344-7efd40c298b1.jpg)
![Screen2](https://user-images.githubusercontent.com/32094266/55056212-d8c1a880-5065-11e9-9b14-8518a4a60d0f.jpg)
![Screen3](https://user-images.githubusercontent.com/32094266/55056213-d8c1a880-5065-11e9-80ef-61e7d44ffcd0.JPG)

**Comment by e-maud** [comment]
Related to timeline under the search bar: would be useful to add a legend and/or specify what the count correponds to (Count of..) in the black box. Thanks!

**Comment by Bunoute** [comment]
Double display of article (might explain/be linked with the double display of the text snippets)
https://impresso-project.ch/alpha/#/issue/JDG-1943-03-22-a/page/JDG-1943-03-22-a-p0002/article/JDG-1943-03-22-a-i0015

**Comment by mduering** [comment]
@PaulSchroeder could you please add a link to the newsletter signup page to https://impresso-project.ch/alpha/#/ ?

**Comment by Bunoute** [comment]
from Milan: 
Scrolling in the search pane is not possible when using Safari (on Mac). The screen jumps back to the top immediately. This makes it impossible to read the topics.

**Comment by Bunoute** [comment]
Milan and I tested also the export function, we receive an empty file, containing only:

<html>
--
<head><title>404 Not   Found</title></head>
<body bgcolor="white">
<center><h1>404 Not   Found</h1></center>
<hr><center>nginx/1.12.2</center>
</body>
</html>

**Comment by danieleguido** [comment]
@Bunoute sorry for that! I did an error on the configuration. Can you try to download the same csv again?

**Comment by Bunoute** [comment]
on the export again:
- many articles are duplicated in multiple versions : of the 2300 articles, it seems there were only 102 unique uid (after the excel remove duplicate option)
- the content is overlapping over several cells (mainly the size): maybe put the content at the end, in the last column?

**Comment by Bunoute** [comment]
From Enrico: overall congratulations!!
On Newspaper page: need information on the language(s) of the newspapers
(On Topic numbers: curious to know how the topic number was chosen)
On user guide: need tips to use the export (import the csv in UFT8 etc.) >> Estelle
On Viewer: when reading the article in image mode, it would be nice to have also the option to add to collection
On search page: setting the dates was a bit tricky but worked + the search button is somewhat hidden down in the pane... but nothing too major.

**Comment by Bunoute** [comment]
Suggestion for the reading mode: would it be possible to read articles from one collection/search result, without going back to the list? e.g. having a "next" button that would take us to the next article of the list, from the collection/result list
see examples at: https://scriptorium.bcu-lausanne.ch/

**Comment by Bunoute** [comment]
On the jobs: the STOP button does not seem to work... does it?

**Comment by Bunoute** [comment]
on the jobs: would it be possible to display the job number on the list of jobs? especially for the downloads, so we know which one we already downloaded?

**Comment by Bunoute** [comment]
On Collections: would it be possible to merge 2 collections? Or when saving a query, add it to an existing collection?

**Comment by mduering** [comment]
Hi Marten, as my feedback form in the interface works not at the moment, I use this way to give another little feedback: I was searching the greek letter α in the NZZ of the 1850ies, because this was actually the sign of the NZZ's correspondent in Paris (and it was put in front of each article written by this correspondent). Unfortunately, I did not get any results. Is it possible that greek letters cannot be searched on the interface? Kind regards and have a nice week-end,
Tobi

**Comment by e-maud** [comment]
A small typo in newspaper timeline page:

"List of newspapers timelines" => "List of newspaper timelines"

and why not simply "Newspaper timelines"?

**Comment by e-maud** [comment]
Strange repetition of article titles and textes on the 4 pages of this issue:
https://impresso-project.ch/alpha/#/issue/GDL-1818-05-22-a/page/GDL-1818-05-22-a-p0004

**Comment by e-maud** [comment]
To read it would be comfortable to be able to remove/hide/toogle (don't know how to say) the Table of content. Some pages are dense and/or bad quality, we need to zoom a lot and it would be nice to have it almost 'full screen'.

**Comment by PaulSchroeder** [comment]
> Strange repetition of article titles and texts on the 4 pages of this issue:
> https://impresso-project.ch/alpha/#/issue/GDL-1818-05-22-a/page/GDL-1818-05-22-a-p0004

the repeated articles articles span over multiple pages. the API returns the article ID for each page it occurs on.

**Comment by mduering** [comment]
On https://impresso-project.ch/branches/fix-filters:

I like the new design! One question: I can drag the time line selection but it does not change anything which is strange. 
To add a filter I need to click Add Filter... - would it make sense to trigger the "Add as Filter" options ("From" "To") the moment one starts dragging the timeline? Or show them all the time?

**Comment by Bunoute** [comment]
On the collection creation: when a name is already used: send a message stating it? now, just API error...
