### ISSUE TITLE
add mailchimp newsletter signup to impresso-project.ch

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#261]
it would be great if people could sign up for impresso news from the project homepage. Mailchimp appear to make it easy to embedd html signup forms:

https://us20.admin.mailchimp.com/lists/integration/embeddedcode?id=19079 

mailchimp login credentials shared via Slack

**Comment by PaulSchroeder** [comment]
i have created a popup and integrated links to navigation and footer.

**Comment by mduering** [comment]
it works well in chrome (with a smal glitch) but not in firefox.. 

<img width="574" alt="image" src="https://user-images.githubusercontent.com/4408050/54110568-fe05b400-43e1-11e9-943d-6b6f947aca51.png">
