### ISSUE TITLE
Publication date in general vs availability in impresso

### ISSUE THREAD

**Issue by simon-clematide** [impresso/impresso-frontend#296]
@Bunoute Could/Should we make a difference between the general availability of a newspaper and the material that is actually our dataset? E.g. NZZ 1780-2017 but only 1780-1950 in our collection.

![image](https://user-images.githubusercontent.com/3041168/57175693-17116b00-6e4f-11e9-97c0-1bce9c7bc302.png)

**Comment by Bunoute** [comment]
yes, it would be good to differentiate both, what has been digitised and what is accessible via impresso

**Comment by PaulSchroeder** [comment]
I have added the dates to the table.
see PR https://github.com/impresso/impresso-frontend/pull/298

would you like to compare the years and display a warning when they differentiate?

**Comment by Bunoute** [comment]
it would be nice to have the difference visible yes, also on the timelines of each newspapers?

**Comment by danieleguido** [comment]
Hi I have just added the `lastIssue` and `firstissue` properties on each newspaper, plus a series of count (artilces, pages, issues)
@PaulSchroeder can you update your PR using the new data model? More info check the PR 
 for impresso-middle-layer https://github.com/impresso/impresso-middle-layer/pull/122
