### ISSUE TITLE
issue viewer: articles not loading properly

### ISSUE THREAD

**Issue by danieleguido** [impresso/impresso-frontend#315]
For many articles:
test https://impresso-project.ch/dev/#/issue/GDL-1952-08-11-a/page/GDL-1952-08-11-a-p0005/article/GDL-1952-08-11-a-i0071

**Comment by tvanbeek** [comment]
seems to work fine?

![image](https://user-images.githubusercontent.com/3518980/58022637-2579ab00-7b0e-11e9-9fdb-f216c1dac751.png)
