### ISSUE TITLE
 Feedback from Beta Release (May 2019)

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#318]
When I click the checkbox on the right, I assume that I add 12 articles to a collection but it's the 10k articles max.
Which is weird since it only found a bit more than 1k and the default description is "All of impresso".

<img width="852" alt="image" src="https://user-images.githubusercontent.com/4408050/57986980-f4e93100-7a7b-11e9-81d9-a0e89865767a.png">

**Comment by mduering** [comment]
I easily loose track of tasks in the Notifications. Add collection name and/or time and date to make it easier to identify them?

<img width="400" alt="image" src="https://user-images.githubusercontent.com/4408050/57987016-42fe3480-7a7c-11e9-9973-f7a924287c94.png">

**Comment by mduering** [comment]
Collection labels only appear after click + apply action

<img width="279" alt="image" src="https://user-images.githubusercontent.com/4408050/57987060-d46da680-7a7c-11e9-884e-a9c9670b351e.png">

**Comment by mduering** [comment]
Selected collections, clicked "apply"

Selected another one:

<img width="388" alt="image" src="https://user-images.githubusercontent.com/4408050/57987102-5958c000-7a7d-11e9-8935-fd894168a4b3.png">

**Comment by mduering** [comment]
Are the counts off?

<img width="393" alt="image" src="https://user-images.githubusercontent.com/4408050/57987124-84dbaa80-7a7d-11e9-9eef-22ef5a6f9f10.png">


<img width="397" alt="image" src="https://user-images.githubusercontent.com/4408050/57987127-945af380-7a7d-11e9-98c9-00d376613b8a.png">

**Comment by Bunoute** [comment]
When you type a KW in the search box, click on search, it turns into a pill but the text remains in the search box 
<img width="380" alt="Screenshot 2019-05-20 07 26 47" src="https://user-images.githubusercontent.com/32094266/57998178-a7e37a00-7ad0-11e9-9ae1-c3292f9447cb.png">

**Comment by Bunoute** [comment]
on the collection filters: there are only 10 items displayed, is it so? :'(  
<img width="1165" alt="Screenshot 2019-05-20 07 49 55" src="https://user-images.githubusercontent.com/32094266/57998952-e464a500-7ad3-11e9-8bb7-aa035cafd680.png">
