### ISSUE TITLE
export CSV - correct STOP fonction and selected export

### ISSUE THREAD

**Issue by Bunoute** [impresso/impresso-frontend#337]
selecting elements for the export fonction does not work: all results from the query are exported

and when trying to stop the export: Error message:
index.js:86 Uncaught (in promise) 
BadRequest
className: "bad-request"
code: 400
data:
status:
code: "NotInArray"
message: "status param is not valid"
ref: ["stop"]
__proto__: Object
__proto__: Object
errors: {}
message: "Error"
name: "BadRequest"
type: "FeathersError"
stack: "BadRequest: Error↵    at new BadRequest (https://impresso-project.ch/app/static/js/vendor.ea157d7cb9785fce4644.js:68695:17)↵    at convert (https://impresso-project.ch/app/static/js/vendor.ea157d7cb9785fce4644.js:68848:7)↵    at Socket.<anonymous> (https://impresso-project.ch/app/static/js/vendor.ea157d7cb9785fce4644.js:65444:17)↵    at Socket.webpackJsonp.AYMf.Socket.onack (https://impresso-project.ch/app/static/js/vendor.ea157d7cb9785fce4644.js:49291:9)↵    at Socket.webpackJsonp.AYMf.Socket.onpacket (https://impresso-project.ch/app/static/js/vendor.ea157d7cb9785fce4644.js:49216:12)↵    at Manager.<anonymous> (https://impresso-project.ch/app/static/js/vendor.ea157d7cb9785fce4644.js:111884:15)↵    at Manager.webpackJsonp.pnVU.Emitter.emit (https://impresso-project.ch/app/static/js/vendor.ea157d7cb9785fce4644.js:101299:20)↵    at Manager.webpackJsonp.Ctjl.Manager.ondecoded (https://impresso-project.ch/app/static/js/vendor.ea157d7cb9785fce4644.js:52133:8)↵    at Decoder.<anonymous> (https://impresso-project.ch/app/static/js/vendor.ea157d7cb9785fce4644.js:111884:15)↵    at Decoder.webpackJsonp.pnVU.Emitter.emit (https://impresso-project.ch/app/static/js/vendor.ea157d7cb9785fce4644.js:101299:20)"
__proto__: FeathersError

**Comment by mduering** [comment]
stop function for saving items to collections does not work either @PaulSchroeder
