### ISSUE TITLE
Adding multiple embeddings should result in an OR query

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#382]
If we want to use word embeddings to broaden our set of keywords/compensate for OCR mistakes, by default this should produce an OR query

**Comment by danieleguido** [comment]
@PaulSchroeder string filter precision must be set to "soft" (it looks for at least one of the words in the query string, it's our OR :)

**Comment by PaulSchroeder** [comment]
fixed and merged to develop !
