### ISSUE TITLE
Trim labels for entites and topics, e.g. "50-Robert Schuman (1,177 results)"

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#406]

**Comment by danieleguido** [comment]
Hi @mduering why topics?

**Comment by mduering** [comment]
we display "fr" with every topic: fr samedi · dimanche · vendredi · lundi · soir
(2,757,177 results)

**Comment by mduering** [comment]
Hi @danieleguido the problem persists for person entities, e.g. 
https://impresso-project.ch/app/#/search?f=%5B%7B%22type%22%3A%22hasTextContents%22%7D,%7B%22type%22%3A%22person%22,%22q%22%3A%5B%22aida-0001-50-Louis-Leopold_Robert%22%5D,%22op%22%3A%22OR%22%7D,%7B%22type%22%3A%22location%22,%22q%22%3A%5B%22aida-0001-54-La_Chaux-de-Fonds%22%5D,%22op%22%3A%22OR%22%7D,%7B%22type%22%3A%22topic%22,%22q%22%3A%5B%22tm-fr-all-v1.0_tp20_fr%22%5D,%22r%22%3A%5B0,1%5D,%22op%22%3A%22OR%22,%22context%22%3A%22include%22%7D%5D&g=articles&p=1&o=-relevance
