### ISSUE TITLE
Table of content: order of articles?

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#416]
On this page https://dev.impresso-project.ch/app/#/issue/IMP-1923-05-19-a/page/IMP-1923-05-19-a-p0008/article/IMP-1923-05-19-a-i0100 

The ad "1 bon acheveur" is placed on top, the ad "Montreux fete de narcisses" second but they are in different positions on the page. How is the position determined?

**Comment by danieleguido** [comment]
The article ordering is based on the layout, normally from top left to bottom right, but it's pretty obscure. I can quickly check in the table of contents endpoint in middle layer
