### ISSUE TITLE
Need to multi-select named entities in Search

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#417]
We are dealing with many duplicate entities e.g. "M. Mitterrand" "Francois Mitterrand" "President Mitterrand". From a user perspective it makes sense to search for all of them ("OR"). 

But in contrast to the other facets, multi-select is laborious for entities: We need to type, select first entity. Then repeat until we have selected all of them.

**Comment by danieleguido** [comment]
Hi @mduering, we can add an option to the autocomplete to open up the entities explorer modal (aka the component `FacetExplorer`). We can filter the list of entities using the current search query. it will be easier there to select multiple entities from the list. What do you think?

**Comment by mduering** [comment]
Hard for me to imagine but sounds good!
