### ISSUE TITLE
high CPU load on search page

### ISSUE THREAD

**Issue by lwieneke** [impresso/impresso-frontend#420]
When working on the search page without any user input the CPU load rises pretty high (see screenshot). Might be related to constant reloads of the IIIF viewer

![Task_Manager_-_Google_Chrome](https://user-images.githubusercontent.com/1942767/63529371-d4aa9180-c504-11e9-9741-216aa95daf09.jpg)

**Comment by danieleguido** [comment]
@tvanbeek can we use lazy load for the IIIF viewers which are not visible?

**Comment by danieleguido** [comment]
should be solved now, IIIF viewers are lazy loaded
