### ISSUE TITLE
images from Luxembourgish newspapers are not displayed

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#424]
as far as I can see this affects all Lux but none of the Swiss newspapers: https://dev.impresso-project.ch/app/#/search/images?f=%5B%7B%22type%22%3A%22daterange%22,%22q%22%3A%5B%221895-12-11T00%3A00%3A00Z%20TO%201935-01-17T23%3A59%3A59Z%22%5D,%22op%22%3A%22OR%22%7D%5D&p=14&o=-date

**Comment by danieleguido** [comment]
It has been fixed, IIIF manifest was missing; however, there are still pages missing in the db, @mromanello is on it.
As you see in the API: https://dev.impresso-project.ch/api/images/?filters[0][type]=title&filters[0][q]=bilder&filters[1][type]=newspaper&filters[1][q]=luxland&limit=1 the IIIF urls point to the eluxemburgensia ones.
