### ISSUE TITLE
Image search results: can't go back to the last result page 

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#426]
Image search results: When I click to read the article in which an image was featured and click the back button in the browser I expect to arrive at the same search result page from which I left but now I am always sent back to page 1. 

The same happens when I search for similar images and click "Remove"

But: it does not happen when I searched for a similar image and then click to inspect an image in the context of an article (screenshot below to help explain this scenario)

![image](https://user-images.githubusercontent.com/4408050/63805514-e97a9100-c919-11e9-9f42-88716b034509.png)

**Comment by danieleguido** [comment]
@tvanbeek can we add a p parameter to the URL?

**Comment by danieleguido** [comment]
Closed, merged into #484
