### ISSUE TITLE
old and new topics: which are active?

### ISSUE THREAD

**Issue by Bunoute** [impresso/impresso-frontend#429]
it is not understandable what topics can still be used as filters and those which are not attached to any article anymore: the "all" topics seem active: https://dev.impresso-project.ch/app/#/topics/tm-fr-all-v1.0_tp43_fr but the "public" topics do not show any article: https://dev.impresso-project.ch/app/#/topics/tm-de-public1_tp30_de
should the "public" topics not appear at all from the frontend?

**Comment by simon-clematide** [comment]
I think this is solved now, as the old topics are gone.
