### ISSUE TITLE
Escher Tageblatt without images

### ISSUE THREAD

**Issue by Bunoute** [impresso/impresso-frontend#439]
articles from the Escher Tageblatt display only the text

ex: https://dev.impresso-project.ch/app/#/issue/tageblatt-1919-08-14-a/page/tageblatt-1919-08-14-a-p0002/article/tageblatt-1919-08-14-a-i0008

but the Obermosel ones seem to be displayed: https://dev.impresso-project.ch/app/#/issue/obermosel-1934-03-19-b/page/obermosel-1934-03-19-b-p0002/article/obermosel-1934-03-19-b-i0017

**Comment by danieleguido** [comment]
Closed as it was due to data ingestion
