### ISSUE TITLE
Post ISR: Problem with "NOT contains" topic?

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#447]
In this query I want to exclude the topic "equipe match club ..."
https://dev.impresso-project.ch/app/#/search?f=%5B%7B%22type%22%3A%22hasTextContents%22%7D,%7B%22type%22%3A%22string%22,%22q%22%3A%22arnhem%22,%22precision%22%3A%22exact%22%7D,%7B%22type%22%3A%22topic%22,%22q%22%3A%5B%22tm-fr-all-v1.0_tp65_fr%22,%22tm-fr-all-v1.0_tp81_fr%22,%22tm-fr-all-v1.0_tp19_fr%22%5D,%22r%22%3A%5B0,1%5D,%22op%22%3A%22OR%22,%22context%22%3A%22exclude%22%7D,%7B%22type%22%3A%22string%22,%22q%22%3A%22vitesse%22,%22precision%22%3A%22exact%22,%22context%22%3A%22exclude%22%7D%5D&g=articles&p=1&o=date 

But I still get this article in the results where the topic scores 65%:
https://dev.impresso-project.ch/app/#/issue/EXP-2001-06-16-a/page/EXP-2001-06-16-a-p0027/article/EXP-2001-06-16-a-i0274

**Comment by danieleguido** [comment]
This is the parsed solrQuery, in effect  

```
filter(content_length_i:[1 TO 10000]) 
AND 
  (content_txt_en:arnhem OR content_txt_fr:arnhem OR content_txt_de:arnhem) 
AND NOT 
  (content_txt_en:vitesse OR content_txt_fr:vitesse OR content_txt_de:vitesse) 
AND filter(*:* AND NOT topics_dpfs:tm-fr-all-v1.0_tp65_fr OR topics_dpfs:tm-fr-all-v1.0_tp81_fr OR topics_dpfs:tm-fr-all-v1.0_tp19_fr)
```

As you see the last filter does not take into account the NOT OR
