### ISSUE TITLE
image search -remove keyword from previous query

### ISSUE THREAD

**Issue by Bunoute** [impresso/impresso-frontend#469]
when searching in the image search: if I use a keyword to search e.g. Jean Paul 
![Screenshot 2019-09-26 at 10 19 49](https://user-images.githubusercontent.com/32094266/65671806-3603da00-e048-11e9-99a5-fbf107ae0119.png)

I then select an image from that result list

![Screenshot 2019-09-26 at 10 20 17](https://user-images.githubusercontent.com/32094266/65671813-3a2ff780-e048-11e9-9613-80fec7e91157.png)

I want to query for that image, without the previous keyword being a filter: I remove the keyword but nothing is displayed anymore

![Screenshot 2019-09-26 at 10 20 35](https://user-images.githubusercontent.com/32094266/65671815-3e5c1500-e048-11e9-8d8e-8b2172604dff.png)

**Comment by danieleguido** [comment]
Closed as it is related to SOLR performance 
https://github.com/impresso/impresso-images/issues/2
