### ISSUE TITLE
Topic assignment numbers displayed in recommender can be wrong

### ISSUE THREAD

**Issue by simon-clematide** [impresso/impresso-frontend#476]
https://impresso-project.ch/app/#/issue/NZZ-1950-11-06-b/page/NZZ-1950-11-06-b-p0022/article/NZZ-1950-11-06-b-i0022
The number in the red circle is very low, at  3%, which would not be high enough for similarity.

![image](https://user-images.githubusercontent.com/3041168/65759656-bd6e4d80-e11b-11e9-879f-3b3c9eed1400.png)

When I go to the article, the topic distribution for zürich · schweiz · mannschaft · minute · zeit ( actually is 87.4 % and not 3%.  There seems to be something mixed up.

https://impresso-project.ch/app/#/issue/NZZ-1931-04-27-b/page/NZZ-1931-04-27-b-p0005/article/NZZ-1931-04-27-b-i0005
![image](https://user-images.githubusercontent.com/3041168/65759714-d4ad3b00-e11b-11e9-82d8-a23611ec5727.png)

**Comment by PaulSchroeder** [comment]
thanks @simon-clematide for the bug report.
it should be fixed with this commit:
https://github.com/impresso/impresso-frontend/pull/480/commits/596b70b82a73a9fdffe9a4cdaa67a47b1125ed19

**Comment by simon-clematide** [comment]
I think the number of the NZZ article are correct now. 

But look at the following: The recommended pages are extremely strange and off-topic. I am sure that there are plenty of military articles in our collection.

https://impresso-project.ch/app/#/issue/luxwort-1915-03-25-a/page/luxwort-1915-03-25-a-p0002/article/luxwort-1915-03-25-a-i0009

**Comment by simon-clematide** [comment]
I think the problem was finally solved in Lausanne.
