### ISSUE TITLE
topic as filters - exclusion ("not containing") does not seem to exclude relevant articles

### ISSUE THREAD

**Issue by Bunoute** [impresso/impresso-frontend#479]
after I selected one topic, with the option "not containing", in my search results, I still had articles with 60% of that topic...
https://impresso-project.ch/app/#/issue/JDG-1982-07-05-a/page/JDG-1982-07-05-a-p0010/article/JDG-1982-07-05-a-i0066

how does the exclusion work? is there a threshold for the topic's presence in the article?

**Comment by simon-clematide** [comment]
From my perspective, this should not happen.  There is a threshold for the topic of at least 1%, I think.  @Bunoute What was your query?

**Comment by Bunoute** [comment]
here is the link to the query: https://impresso-project.ch/app/#/search?f=%5B%7B%22type%22%3A%22hasTextContents%22%7D,%7B%22type%22%3A%22string%22,%22q%22%3A%22feyler%22,%22precision%22%3A%22exact%22%7D,%7B%22type%22%3A%22topic%22,%22q%22%3A%5B%22tm-fr-all-v1.0_tp48_fr%22%5D,%22r%22%3A%5B0,1%5D,%22op%22%3A%22OR%22,%22context%22%3A%22exclude%22%7D%5D&g=articles&p=1&o=-relevance

**Comment by simon-clematide** [comment]
Ok, the article links to  topic https://impresso-project.ch/app/#/topics/tm-fr-all-v1.0_tp51_fr
But you excluded topic 48.. Which in turn shows very strange articles.... So I suppose the problems are  twofold... Solr indexes on topics and topics assigned to articles.. or a caching problem somewhere in the middleware.  @e-maud Makes that sense?

![image](https://user-images.githubusercontent.com/3041168/65770995-8b6ae480-e137-11e9-9bcd-d07bc3be709e.png)

**Comment by simon-clematide** [comment]
@danieleguido  The search query still gives back old topics "public1.1_tp14_fr" in the completion.
@e-maud Do we have them still in the solr topic autocompletion index?
https://impresso-project.ch/app/#/search?f=%5B%7B"type"%3A"topic","q"%3A%5B"tm-fr-public1.1_tp14_fr"%5D,"r"%3A%5B0,1%5D,"op"%3A"OR","context"%3A"include"%7D%5D&g=articles&p=1&o=-relevance

**Comment by danieleguido** [comment]
Hi all, if I sum up, it seems that @Bunoute's query excluded `tm-fr-all-v1.0_tp48_fr`; the `tm-fr-all-v1.0_tp51_fr` is very similar to it, but the top articles are very strange. Can we close this issue in this repo and move to an ingestion related repo @simon-clematide @e-maud ?

**Comment by simon-clematide** [comment]
Yes, the crucial question for the middleware is (a) whether it knows something about which topic models it should actually query, or (b) whether it is agnostic and just delivers whatever the solr endpoint delivers.
I think (b) should be the way to go.
