### ISSUE TITLE
topics as filters: OR/AND by default 

### ISSUE THREAD

**Issue by Bunoute** [impresso/impresso-frontend#501]
when I perform a query and select the topics as filters from the left pane, the default combination of the topics is "OR" but when I click on explore and select from there, it become "AND"... shouldn't it be the same settings for both?
because then, the result is null...

I was trying to exclude articles without topics by selecting all topics:

Found 0 articles published from jan 1, 1900 to jan 1, 1945 containing rigassi with topic "journal · fait · question · point · chose" or "parti · gouvernement · socialiste · politique · pouvoir" or "comité · membre · président · assemblée · association" or "peuple · esprit · vie · liberté · foi" or "guerre · paix · pays · peuple · politique" or "point · question · problème · fait · vue" or "loi · droit · initiative · canton · projet" or "élection · parti · candidat · voix · liste", "commission · projet · loi · proposition · conseil" or "ministre · président · gouvernement · affaire · chef" or "chambre · gouvernement · ministre · député · ministère" or "gouvernement · accord · conférence · question · traité" or "industrie · commerce · produit · pays · exportation" or "livre · auteur · histoire · ouvrage · page" or "professeur · université · science · étudiant · étude", "travail · santé · argent · vie · affaire" or "tribunal · droit · loi · article · cas" or "école · cour · élève · classe · enseignement" or "affaire · cour · juge · procès · enquête" or "action · administration · société · conseil · actionnaire" or "président · force · gouvernement · pays · mort" or "cour · nom · fin · bourse · action" or "travail · ouvrier · assurance · grève · salaire" or "canton · projet · centre · région · problème" and "professeur · université · science · étudiant · étude" or "commission · projet · loi · proposition · conseil" or "pièce · appartement · bain · confort · vue" or "comité · membre · président · assemblée · association" or "président · force · gouvernement · pays · mort" or "travail · santé · argent · vie · affaire" or "élection · parti · candidat · voix · liste" or "pays · économie · marché · politique · mesure"

https://impresso-project.ch/app/#/search?f=%5B%7B%22type%22%3A%22hasTextContents%22%7D,%7B%22type%22%3A%22daterange%22,%22q%22%3A%5B%221900-01-01T00%3A00%3A00Z%20TO%201944-12-31T23%3A59%3A59Z%22%5D,%22op%22%3A%22OR%22%7D,%7B%22type%22%3A%22string%22,%22q%22%3A%22rigassi%22,%22precision%22%3A%22exact%22%7D,%7B%22type%22%3A%22topic%22,%22q%22%3A%5B%22tm-fr-all-v1.0_tp58_fr%22,%22tm-fr-all-v1.0_tp94_fr%22,%22tm-fr-all-v1.0_tp23_fr%22,%22tm-fr-all-v1.0_tp01_fr%22,%22tm-fr-all-v1.0_tp71_fr%22,%22tm-fr-all-v1.0_tp02_fr%22,%22tm-fr-all-v1.0_tp41_fr%22,%22tm-fr-all-v1.0_tp59_fr%22%5D,%22r%22%3A%5B0,1%5D,%22op%22%3A%22OR%22,%22context%22%3A%22include%22%7D,%7B%22type%22%3A%22topic%22,%22q%22%3A%5B%22tm-fr-all-v1.0_tp09_fr%22,%22tm-fr-all-v1.0_tp95_fr%22,%22tm-fr-all-v1.0_tp91_fr%22,%22tm-fr-all-v1.0_tp93_fr%22,%22tm-fr-all-v1.0_tp84_fr%22,%22tm-fr-all-v1.0_tp77_fr%22,%22tm-fr-all-v1.0_tp06_fr%22%5D,%22r%22%3A%5B0,1%5D,%22op%22%3A%22OR%22,%22context%22%3A%22include%22%7D,%7B%22type%22%3A%22topic%22,%22q%22%3A%5B%22tm-fr-all-v1.0_tp57_fr%22,%22tm-fr-all-v1.0_tp67_fr%22,%22tm-fr-all-v1.0_tp69_fr%22,%22tm-fr-all-v1.0_tp76_fr%22,%22tm-fr-all-v1.0_tp34_fr%22,%22tm-fr-all-v1.0_tp55_fr%22,%22tm-fr-all-v1.0_tp62_fr%22,%22tm-fr-all-v1.0_tp78_fr%22,%22tm-fr-all-v1.0_tp90_fr%22%5D,%22r%22%3A%5B0,1%5D,%22op%22%3A%22OR%22,%22context%22%3A%22include%22%7D,%7B%22type%22%3A%22topic%22,%22q%22%3A%5B%22tm-fr-all-v1.0_tp06_fr%22,%22tm-fr-all-v1.0_tp09_fr%22,%22tm-fr-all-v1.0_tp18_fr%22,%22tm-fr-all-v1.0_tp23_fr%22,%22tm-fr-all-v1.0_tp55_fr%22,%22tm-fr-all-v1.0_tp57_fr%22,%22tm-fr-all-v1.0_tp59_fr%22,%22tm-fr-all-v1.0_tp63_fr%22%5D,%22r%22%3A%5B0,1%5D,%22op%22%3A%22OR%22,%22context%22%3A%22include%22%7D%5D&g=articles&p=1&o=-relevance

**Comment by danieleguido** [comment]
closed as solved
