### ISSUE TITLE
Quoting of special characters in similar word lookup

### ISSUE THREAD

**Issue by simon-clematide** [impresso/impresso-frontend#516]
@danieleguido I do not know whom to address with this issue, so you are the default one... sorry.
There is an error with certain characters in the lookup of similar words:

![image](https://user-images.githubusercontent.com/3041168/67863167-af00c080-fb23-11e9-8c32-ff30d9ba86d5.png)

Note, that the case where the word is not known is treated correctly.
![image](https://user-images.githubusercontent.com/3041168/67863251-d788ba80-fb23-11e9-870f-f5df7d66d0e4.png)

Maybe the interface should generally be robust with respect to special characters (e.g. the interface crashes with a search word like "geéondl)é").

**Comment by danieleguido** [comment]
Thanks @simon-clematide. Here's how I'd proceed:
- [ ] split the query into words, then take the longest word to get the similar words (at least we have some results)
- [ ] add escaping for solr sensitive characters (this is a general issue indeed)

**Comment by danieleguido** [comment]
Finally, solr escaping was not needed here as I split for non word characters.

**Comment by simon-clematide** [comment]
Just to remind you that Luxembourgish had this strange orthography of using ' within words for vowel length, strength or quality (I don't remember exactly...) anyway, that's why one newspaper is even called "Unio'n"
