### ISSUE TITLE
in the article viewer: correct the message of missing facsimile

### ISSUE THREAD

**Issue by Bunoute** [impresso/impresso-frontend#586]
in the viewer, in close reading mode, when the facsimile of the article is missing, we can read:
Note: Facsimile could not be retrieve for this specific article. To read it in its digitized version, switch to "image mode" 

could it be:

Note: Facsimile could not be retrieved for this specific article. To read it in its digitised version, switch to "view in context" mode.

**Comment by danieleguido** [comment]
integrated in #974
