### ISSUE TITLE
entity overlays not working?

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#592]
https://dev.impresso-project.ch/app/issue/indeplux-1883-03-18-a/page/indeplux-1883-03-18-a-p0001/article/indeplux-1883-03-18-a-i0006

**Comment by danieleguido** [comment]
Not in article text regions, to be fixed.

**Comment by danieleguido** [comment]
THere is no entity id specified, need to be downloaded from the database. Cannot fix for the moment!

**Comment by danieleguido** [comment]
sql query to get mention offsets:

```sql
SELECT start_offset,length,entity_id FROM mentions
 WHERE ci_id="LSE-1924-03-07-a-i0067";
```
