### ISSUE TITLE
Which is the correct link to newspapers page?

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#598]
Should the link in the newspaper corpus FAQs https://dev.impresso-project.ch/app/faq#which-newspapers refer to https://impresso-project.ch/app/#/newspapers or to https://impresso-project.ch/app/newspapers ?

**Comment by danieleguido** [comment]
The right link is https://impresso-project.ch/app/newspapers as we got rid of the # character to route to pages
