### ISSUE TITLE
disapearing quotation mark from the search box

### ISSUE THREAD

**Issue by Bunoute** [impresso/impresso-frontend#6]
when I type a few words within quotation mark in the search box of the homepage (https://impresso-project.ch/v1/#/) one of them disappears when I hit "go".
For instance I type "votation fédérale", hit "go", it leads me to 0 hit and "votation fédérale
I manually add the missing quotation mark and it works.

**Comment by tvanbeek** [comment]
suggestions endpoint returns bad request when searching for quoted strings:

`56:4253["find","suggestions",{"q":"\"test123\"","limit":10}]`
