### ISSUE TITLE
Entity page / Mentions: Error message

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#607]
https://dev.impresso-project.ch/app/entities/aida-0001-50-Rue_Neuve_(Brussels)?tab=mentions

{ "route": [ "mentions", "find" ], "message": "Error", "code": 400, "name": "BadRequest" } paths.mentions.find

**Comment by danieleguido** [comment]
Fixed in middle-layer, branch develop, to be released soon!
