### ISSUE TITLE
Display of individual issues (first pages) for newspapers

### ISSUE THREAD

**Issue by lwieneke** [impresso/impresso-frontend#645]
Very slow or no loading at all for issues/first pages in the newspaper view.
https://impresso-project.ch/app/newspapers/armeteufel

<img width="1627" alt="impresso___Media_Monitoring_of_the_Past" src="https://user-images.githubusercontent.com/1942767/72742469-14f06780-3baa-11ea-9646-63b439194225.png">

**Comment by danieleguido** [comment]
troubles in external IIIF server, should be fixed now.
