### ISSUE TITLE
FAQ - Why can’t I see everything? How do I get access to the full corpus?

### ISSUE THREAD

**Issue by e-maud** [impresso/impresso-frontend#664]
> we can only show a subset of the newspapers which have been made available in the public domain. To gain access to the whole collection, you need to sign a Non Disclosure Agreement (NDA).

Suggestion:
Unrestricted access is only possible for the subset of newspapers which are in the public domain. To gain access to the whole collection, you need to sign a Non Disclosure Agreement (NDA).

(`we can only show` suggests that we show only these ones, while we show everything, it's more a question  of access)

> From a legal perspective, there is a risk that content creators could make claims to their rights to texts and images which were published in a newspaper. This is why we can only show a subset of the newspapers which have been made available in the public domain. To gain access to the whole collection, you need to sign a Non Disclosure Agreement (NDA). We will provide you with a user account once we receive the signed NDA from you.

=>  From a legal perspective, there is a risk that content creators could make claims to their rights to texts and images which were published in a newspaper. This is why **unrestricted access is only possible for the subset of newspapers which are in the public domain**. To gain access to the whole collection, you need to sign a Non Disclosure Agreement (NDA). We will provide you with a user account **upon reception of your signed NDA (digital format is ok)**.

> Please see the Terms of Use to learn more about the usage rights for the impresso corpus.

link to the ToU page should be added

**Comment by e-maud** [comment]
Sorry but idem, have this been taken into account? There is still a missing link, as well as a misleading wording (according to me).

**Comment by Bunoute** [comment]
it is being released now, in the correct version
