### ISSUE TITLE
Terms of Use: finalization

### ISSUE THREAD

**Issue by e-maud** [impresso/impresso-frontend#667]
Hello @Bunoute and @mduering ,

I think the last coherence/finalization steps for the ToU explanations on the interface are still missing:

- **right statement individual pages**

In the FAQ (What are the copyrights of the newspapers accessible through the impresso interface?), in the popup at the beginning of the session, and on the Terms of Use page, it is referred to 2 pages which do not exist:

"The majority of them are free of use for personal and academic use (see the ‘Personal and Academic use’ license page). Others are not subject to any restrictions (see the ‘Public’ License page). "

Either we create those pages, either the text needs to be modified.

Originally the idea was to have pages (e.g. `impresso-project/license-academic, impresso-project/license-public, etc.) describing the right statements, and those links would be in the CSV export for each article (instead of the word 'open/close/etc').

I think having dedicated pages is still useful, but perhaps not mandatory right now (?)

- **right statement display locations in the interface**

> Conditions of use are set at the issue level of each newspaper. You can find this information a) in the newspaper page, b) in the article view of impresso interface, and c) upon download, for each item of the CSV file.

These are the 3 locations I imagined to let the user know about the license, but is it the case?

- **coherence of naming**
Does the document that users needs to sign contain the same text as the session-start-popup?

**Comment by Bunoute** [comment]
we could replace "page" by "ToU section" in the FAQ?

Indeed, at the article level, it is not visible, only the filter in the search page indicates it at article level. Do we really need to display it in the viewer ? There are already so many information...
could we instead rephrase and state:

Conditions of use are set at the issue level of each newspaper. You can find this information a) in the *individual* newspaper page, b) upon download, for each item of the CSV file. To select articles belonging to a particular category of license, choose the relevant category in "filter by access rights".

And here it would be good to harmonise indeed:
OpenPrivate > Personal Use
Closed > Online use only (?)
OpenPublic > Public License
not specified : same

**Comment by e-maud** [comment]
- Yes, referring to ToU section is a nice option. Then in the ToU I would put in bold `personal and academic use include the following`, plus add again something on public domain, e.g. **As per public domain**, digital documents may be used without any restrictions.

- Yes, no more info on the viewer. At the time I was rather thinking of a little flag in the TOC, but Daniele would know better. In the rephrasing:
     -  "in the individual newspaper page," => on the ... ?
     -  still having a) on the newspaper page (it is in the metadata)

- And yes, it would be helpful to harmonize the denomination in the filter, but this is rather for Daniele, I will open an issue just on that:
OpenPrivate > Personal use
Closed > Personal use (no export)
OpenPublic > Public domain

For the not specified, Daniele should map it towards `Personal use (no export)`. I will check in the DB first.
