### ISSUE TITLE
Consistent terminology: article vs. content item

### ISSUE THREAD

**Issue by simon-clematide** [impresso/impresso-frontend#674]
I think we should tighten our terminology. The interface reports its results in many places, e.g. search hit graphs, with "articles". In other places (blogs etc.) we use the technically more precise term "content item", which, however, is less telling to outsiders and maybe a bit cumbersome. I think we should stick to a consistent terminology. I could live with a broader term "article" that includes everything from advertisements to "page articles" to real articles.

What's your opinion?

@maud @danieleguido

**Comment by danieleguido** [comment]
I'd keep articles on the front-end as well

**Comment by e-maud** [comment]
yes, "articles" is easier for everybody in the front end.
