### ISSUE TITLE
Statistical numbers and the text don't add up

### ISSUE THREAD

**Issue by simon-clematide** [impresso/impresso-frontend#676]
We cannot write 5.445.888 million pages (this would be 5.445.888.000.000 pages... It is either 5.445.888 pages of 5.4 million pages.
![image](https://user-images.githubusercontent.com/3041168/72882993-d373cf80-3d03-11ea-9572-9e21b36f094d.png)

**Comment by danieleguido** [comment]
Should be fixed in current dev (and latest docker) https://dev.impresso-project.ch/app/
