### ISSUE TITLE
Absolute and relative counts in image search

### ISSUE THREAD

**Issue by simon-clematide** [impresso/impresso-frontend#680]
The absolute counts (SUM) work as expected:

![image](https://user-images.githubusercontent.com/3041168/72972497-d508ca80-3dcb-11ea-90a8-c83e878e7f3c.png)

But what would be the meaning of the relative count if no further search criteria is applied?  Should not all of them be 1? (Here is the query : https://impresso-project.ch/app/search/images?f=%5B%7B%22type%22%3A%22daterange%22,%22q%22%3A%5B%221737-01-01T00%3A00%3A00Z%20TO%201851-06-13T23%3A59%3A59Z%22%5D,%22op%22%3A%22OR%22%7D%5D&g=articles) 
![image](https://user-images.githubusercontent.com/3041168/72972769-53fe0300-3dcc-11ea-87e8-c91f4341b198.png)

**Comment by danieleguido** [comment]
true, I have to double check ...
