### ISSUE TITLE
impresso project page: remove Sixth Workshop and add ForumZ on 19.5.

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#687]
..from the event calendar that is :-)

**Comment by PaulSchroeder** [comment]
I added ForumZ but missing more info on location, time etc.

**Comment by mduering** [comment]
Hi Paul, many thanks - 19.5. ; 18.00 - 20.00 at National Library of Luxembourg

**Comment by PaulSchroeder** [comment]
updated the event details. dankeschön.
