### ISSUE TITLE
homepage: update sample queries

### ISSUE THREAD

**Issue by simon-clematide** [impresso/impresso-frontend#688]
If topics are referenced in the sample queries on the homepage https://dev.impresso-project.ch/app then they must be changed to currently existing topics.

**Comment by danieleguido** [comment]
Reported from the latest UX test, label as high priority

**Comment by danieleguido** [comment]
- [ ] Sample queries on homepage contain search criteria with topics no longer available

- [ ] queries are now serialised differently

**Comment by danieleguido** [comment]
updated wishlist for the homepage:

- [ ] Remove the videos (keep for archive though)
- [ ] Keep “Perform this query” but take examples from Challenges. We keep the display of Challenges as is and below give some previews of what to expect illustrated by gifs/screenshots and links to concrete queries
- [ ] Display screenshots of search pills based on the queries
- [ ] Update data rundown

**Comment by danieleguido** [comment]
see #1047
