### ISSUE TITLE
Repeated line in article view

### ISSUE THREAD

**Issue by simon-clematide** [impresso/impresso-frontend#691]
The line of the preceding region is sometimes repeated in the next region. Not sure whether this is a fronend issue or comes from the data.
See e.g. 
https://impresso-project.ch/app/issue/onsjongen-1950-02-01-a/page/onsjongen-1950-02-01-a-p0007/article/onsjongen-1950-02-01-a-i0004

**Comment by danieleguido** [comment]
this has been fixed in the current develop release by @theorm: https://dev.impresso-project.ch/app/issue/onsjongen-1950-02-01-a/page/onsjongen-1950-02-01-a-p0007/article/onsjongen-1950-02-01-a-i0004?tab=toc
