### ISSUE TITLE
Arcadia: error message { "route": [ "search-facets", "get" ], "message": "Error", "code": 400, "name": "BadRequest" }paths.search-facets.get

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#702]
![image](https://user-images.githubusercontent.com/4408050/73534290-10854380-4421-11ea-933d-f2e18b9b4973.png)

via tawk.to, no more info

**Comment by danieleguido** [comment]
Did you get the URL of the page?

**Comment by mduering** [comment]
sorry, no missed it
