### ISSUE TITLE
Article viewer: small problem with display of topics

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#722]
![grafik](https://user-images.githubusercontent.com/4408050/73939236-53e02600-48e9-11ea-8846-f3a1da612458.png)

https://impresso-project.ch/app/issue/IMP-1916-07-29-a/page/IMP-1916-07-29-a-p0001/article/IMP-1916-07-29-a-i0002

**Comment by danieleguido** [comment]
cannot reproduce; however we have to improve article view layout in #974
