### ISSUE TITLE
 Slack link is broken

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#728]
![grafik](https://user-images.githubusercontent.com/4408050/73971858-fe733b80-491f-11ea-8d50-88c1259f417b.png)

**Comment by danieleguido** [comment]
Every #citizenscientist is a researcher ;)
We are researcherfluid, we can offer the possibility of having a specific label! 
1. user
2. researcher
...
23. Not sure
24. Rather not say
25. Others (please state)

**Comment by danieleguido** [comment]
btw @mduering can you give me the updated link?

**Comment by mduering** [comment]
I cannot generate it, it seems restricted for the admins. I'll send Estelle an email to make me one

**Comment by danieleguido** [comment]
Updated!
