### ISSUE TITLE
I&C error

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#744]
https://impresso-project.ch/app/compare?left=CgwYByABKgZhcm5oZW0%3D&right=c%3Aunknown-collection-id 

{ "route": [ "collections", "get" ], "message": "Error", "code": 404, "name": "NotFound" } paths.collections.get
{ "route": [ "search-queries-comparison", "create" ], "message": "server error", "code": 500, "name": "GeneralError" } paths.search-queries-comparison.create

not sure what is going on but it seems as if toggling between Query and Collections causes problems. 
What actually happens when we do? Is the previous selection void or is it kept in consideration? Both would be plausible.

**Comment by theorm** [comment]
This has already been fixed in dev. Will be deployed with the next release.
