### ISSUE TITLE
Backspace key triggers browser "Back" function when trying to edit a keyword

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#751]
the most annoying bug so far in my experience :-)

happens in Search but also Word embeddings

**Comment by theorm** [comment]
Which browser do you use @mduering ? I just tried in Chrome and it does not trigger navigation.

**Comment by mduering** [comment]
@theorm I used Firefox but tried unsuccessfully to reproduce it now, so was fixed along the way - I will close this :-)

**Comment by mduering** [comment]
it seems the problem persists with arrow keys in Firefox 74

**Comment by danieleguido** [comment]
Cannot reproduce it in firefox 74. Can you do a screencast?

**Comment by danieleguido** [comment]
Closing for now, please open t again if the problem still persists
