### ISSUE TITLE
Percentages in ngram not working properly?

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#752]
via tawk:

: | impresso-project.ch
-- | --
Submitted From | : | https://impresso-project.ch/app/search/ngrams?f=%5B%5D&unigram=computer
Name | : | Michael Geiss
Email | : | mgeiss@ife.uzh.ch
Message | : | Dear all, Is it possible that the percentage function does not work with  the Ngrams? It does not show it correctly in the small as well as in  the large window. This applies to both Firefox and Safari. Many thanks!  Michael

**Comment by danieleguido** [comment]
Hi @mduering, this should be fixed in the current dev release

**Comment by mduering** [comment]
Ok thanks for the update

**Comment by theorm** [comment]
I just assume it has been fixed (we reworked Ngram page). Please reopen if it needed.
