### ISSUE TITLE
x axes of topics pages are strange and inconsistent with respect to articles shown for a topic

### ISSUE THREAD

**Issue by simon-clematide** [impresso/impresso-frontend#758]
The timeline of a topic limits the years shown in a strange way that does not match the view of article. E.g. the following topic https://impresso-project.ch/app/topics/tm-de-all-v2.0_tp30_de?tab=articles has a hit in 1780. 
![image](https://user-images.githubusercontent.com/3041168/75229765-dbb3a480-57b2-11ea-8038-18e043ff2c7a.png)
But the timeline only starts at 1937.
![image](https://user-images.githubusercontent.com/3041168/75229898-1ae1f580-57b3-11ea-8b23-02851c6f04e1.png)

**Comment by e-maud** [comment]
A few more examples:
The topic with "guerre" https://impresso-project.ch/app/topics/tm-fr-all-v2.0_tp29_fr has 0 hit in the topic timeline in the topic view

![image](https://user-images.githubusercontent.com/10697182/75367042-f758a100-58bf-11ea-9db4-6050a4971654.png)

but in the search page quite some articles are shown for the same period

![image](https://user-images.githubusercontent.com/10697182/75367137-18b98d00-58c0-11ea-8799-5a4f3ea1b90e.png)

**Comment by danieleguido** [comment]
solr request from middle layer is correct though:

    /select?q=filter(topics_dpfs:tm-fr-all-v2.0_tp46_fr)&facet=on&facet.field=meta_year_i&rows=0`

corresponding api query is **not** giving the same results:

    http://localhost:3030/search-facets/year?group_by=articles&filters[0][type]=topic&filters[0][q]=tm-fr-all-v2.0_tp46_fr

while adding a proper limit helps:

    http://localhost:3030/search-facets/year?group_by=articles&filters[0][type]=topic&filters[0][q]=tm-fr-all-v2.0_tp46_fr&limit=300

to be integrated in search store, method LOAD_TIMELINE

**Comment by danieleguido** [comment]
Fixed, will become available in the next release.
have a look in our dev: https://dev.impresso-project.ch/app/topics/tm-fr-all-v2.0_tp29_fr
