### ISSUE TITLE
from I&C to search page: overlap turns into "OR" query (instead of "AND")

### ISSUE THREAD

**Issue by Bunoute** [impresso/impresso-frontend#761]
https://impresso-project.ch/app/compare?left=CiIQAhgQKhxhaWRhLTAwMDEtNTAtUm9iZXJ0X1NjaHVtYW5u&right=CiEQAhgQKhthaWRhLTAwMDEtNTAtUm9iZXJ0X1NjaHVtYW4%3D

When I want to see the 62 articles that are in the overlap column, containing the NE Robert Schuman and NE Robert Schumann, I click on "open in search page" but it creates an "OR" query: 
https://impresso-project.ch/app/search?f=%5B%7B%22op%22%3A%22OR%22,%22type%22%3A%22person%22,%22q%22%3A%22aida-0001-50-Robert_Schumann%22%7D,%7B%22op%22%3A%22OR%22,%22type%22%3A%22person%22,%22q%22%3A%22aida-0001-50-Robert_Schuman%22%7D%5D&g=articles

**Comment by theorm** [comment]
This is how search page groups filters. 

@danieleguido the code [here](https://github.com/impresso/impresso-frontend/blob/develop/src/models/SearchQuery.js#L94) merges two filters of the same kind with whatever operator defined in the first of them which is quite random and incorrect. What is the reason of this merge? Can we remove it? This would fix this problem.

**Comment by c2dhautomaton** [comment]
Yes, we should modify to take into account different operators. The merge is mainly used by the autocomplete to avoid too many filters of the same type, so we cannot remove it. I suggest to add the operator `op` to the condition at [L 79](https://github.com/impresso/impresso-frontend/blob/develop/src/models/SearchQuery.js#L79), what do you think?

**Comment by theorm** [comment]
I don't think adding `op` will fix it. In the Robert Schumann example both filters have `op` set to `OR` so they will be equal and will `OR`-ed anyway.

**Comment by theorm** [comment]
It sounds like this should be fixed in autocomplete then. I'll have a look.

**Comment by theorm** [comment]
Hi @Bunoute . This should now be fixed on preprod. Can you try please?
