### ISSUE TITLE
bug: { "route": [ "issues", "get" ], "message": "Error", "code": 501, "name": "NotImplemented" } paths.issues.get

### ISSUE THREAD

**Issue by Bunoute** [impresso/impresso-frontend#762]
nothing loaded for this page:
https://impresso-project.ch/app/issue/FZG-1972-04-28-a/page/FZG-1972-04-28-a-p0011/article/FZG-1972-04-28-a-i0064
no facsimile, no table of contents, no transcripts...

**Comment by danieleguido** [comment]
I think it is related to data, I have to check.

**Comment by theorm** [comment]
Should be fixed in https://github.com/impresso/impresso-middle-layer/pull/270

**Comment by theorm** [comment]
Has been fixed in preprod (https://dev.impresso-project.ch/app/issue/FZG-1972-04-28-a/page/FZG-1972-04-28-a-p0011/article/FZG-1972-04-28-a-i0064). @Bunoute can you check please?

**Comment by Bunoute** [comment]
all looks well indeed!
everything is normal and the absence of facsimile in the transcription view is explained. I'll transmit that to the user that needed it, thanks on her behalf!
Note: Facsimile could not be retrieve for this specific article. To read it in its digitized version, switch to "Facsimile view"
