### ISSUE TITLE
on DEV - image search result do not load

### ISSUE THREAD

**Issue by Bunoute** [impresso/impresso-frontend#785]
No results for: https://dev.impresso-project.ch/app/search/images?o=-date&p=1&f=%5B%7B%22type%22%3A%22hasTextContents%22%7D,%7B%22type%22%3A%22title%22,%22q%22%3A%22dreyfus%22,%22precision%22%3A%22exact%22%7D%5D

**Comment by danieleguido** [comment]
Should be fixed now in current dev
