### ISSUE TITLE
why is there no more the "more" button on current dev, for the filters in the search page?

### ISSUE THREAD

**Issue by Bunoute** [impresso/impresso-frontend#790]
in the current app:
<img width="407" alt="Screenshot 2020-03-16 at 11 11 25" src="https://user-images.githubusercontent.com/32094266/76746056-2a7fa900-6777-11ea-9760-83175c61e012.png">

in the current dev:
<img width="407" alt="Screenshot 2020-03-16 at 11 11 47" src="https://user-images.githubusercontent.com/32094266/76746036-25225e80-6777-11ea-8c39-a48a57ace92c.png">

**Comment by danieleguido** [comment]
Left out ! sorry

**Comment by theorm** [comment]
The "more..." button has been replaced with "show all...". Let us know if something still doesn't work.

**Comment by Bunoute** [comment]
it works very nice but when I click on "show all", I see all topics from impresso, without any relation with the current query, so if I wanted to see, for instance, the relevant topics to the current query, I have to click randomly until I find the relevant ones... could this "show all" order the topics, NE etc. by relevance to the current query?

for instance: https://dev.impresso-project.ch/app/search?f=%5B%7B%22type%22%3A%22title%22,%22op%22%3A%22OR%22,%22q%22%3A%5B%22dreyfus%22%5D,%22precision%22%3A%22exact%22%7D%5D&g=articles

<img width="882" alt="Screenshot 2020-03-19 at 12 01 04" src="https://user-images.githubusercontent.com/32094266/77060740-64e88080-69d9-11ea-9616-01ab6fd024a7.png">

**Comment by danieleguido** [comment]
hi @Bunoute I started redesign the more function from the ground up:
- put back the "more..."  button that just adds the next options directly in the list
- add a "add filter button next to the autocomplete, and have the whole list of available filter in the explorer. 
What do you think?

**Comment by Bunoute** [comment]
just like in I&C? that sounds good!

**Comment by danieleguido** [comment]
yep, something like this?
<img width="386" alt="Screenshot 2020-03-20 at 14 14 16" src="https://user-images.githubusercontent.com/1181642/77166778-20caae00-6ab5-11ea-96d2-8dfc995aacec.png">

**Comment by danieleguido** [comment]
SHould be fixed, but please feel free to reopen if necessary.
