### ISSUE TITLE
Search results not displayed, but can be saved to a collection

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#791]
this is very weird: when I search for "herero" with time filter it finds 37 articles but does not display them in Search. I can save them to a collection and retrieve there. If I edit the search pill to eg "alpaca" it works as expected. If I search for "herero" without time filter it also works

https://dev.impresso-project.ch/app/search?f=%5B%7B%22type%22%3A%22hasTextContents%22%7D,%7B%22type%22%3A%22isFront%22%7D,%7B%22type%22%3A%22string%22,%22q%22%3A%22herero%22,%22precision%22%3A%22exact%22%7D,%7B%22type%22%3A%22daterange%22,%22q%22%3A%5B%221882-01-01T00%3A00%3A00Z%20TO%201913-09-29T23%3A59%3A59Z%22%5D,%22op%22%3A%22OR%22%7D%5D&g=articles&p=6&o=-relevance

**Comment by danieleguido** [comment]
@mduering is it still the case?

**Comment by danieleguido** [comment]
Apparently you had p=6 in your URL while there were only 37 results (12 per pages)

**Comment by mduering** [comment]
many thanks @danieleguido for checking - that makes sense. Is there a straightforward way to reset the page count so this weird thing can not happen anymore?

**Comment by danieleguido** [comment]
Well, there was such a mechanism in place, during the refactoring something has been left behind :)

**Comment by mduering** [comment]
ok, thanks!

**Comment by theorm** [comment]
@mduering this has been fixed in preprod. We now reset the page number every time filters change and it should not be possible to arrive at an empty page anymore. Can you please confirm?

However the link above will still show an empty page. We can consider it now a link that you should not be able to create using Impresso webapp. :)

**Comment by mduering** [comment]
works fine now, thanks!
