### ISSUE TITLE
in I&C, error message when selecting a collection in column B

### ISSUE THREAD

**Issue by Bunoute** [impresso/impresso-frontend#792]
when in I&C, in. DEV, I selected a collection in column A, and then go to select another collection in column B this message appears: { "route": [ "search-queries-comparison", "create" ], "message": "server error", "code": 500, "name": "GeneralError" } paths.search-queries-comparison.create

**Comment by Bunoute** [comment]
I still can select one collection, it's not a problem, there is just systematically this message that appears...

**Comment by theorm** [comment]
@Bunoute can you add a link to the page after you select a collection in column A?

**Comment by Bunoute** [comment]
it was the case with every collection that I selected, in column a and it appeared when I clicked on the "collections" tab in column b. Now not any more :)

**Comment by theorm** [comment]
Ok great, I'll close it then!

**Comment by Bunoute** [comment]
maybe it is related: when I compare two queries, but remove the queried KW in column B, this appears: Bad request. paths.search-queries-comparison.create. 
and here the URL: https://dev.impresso-project.ch/app/compare?left=Cg8QAhgDIAEqB2RyZXlmdXM%3D&right=

**Comment by theorm** [comment]
Don't know if it is related but I managed to reproduce the second error. It is now fixed. Can you check?
