### ISSUE TITLE
Bad request. paths.search.find when going from I&C to search page

### ISSUE THREAD

**Issue by Bunoute** [impresso/impresso-frontend#793]
when in I&C in DEV, i selected two collections and try to "open" the overlap "in search page", it tells me I did a bad request...

https://dev.impresso-project.ch/app/compare?left=c%3Alocal-mamu-CCUnstkt&right=c%3Alocal-mamu-zfuzF2sQ

**Comment by theorm** [comment]
This should be fixed now: https://github.com/impresso/impresso-frontend/pull/797

**Comment by theorm** [comment]
@Bunoute feel free to reopen if it is still not working.
