### ISSUE TITLE
KW search in title does not seem to work...

### ISSUE THREAD

**Issue by Bunoute** [impresso/impresso-frontend#799]
https://dev.impresso-project.ch/app/search?f=%5B%7B%22type%22%3A%22title%22,%22op%22%3A%22AND%22,%22q%22%3A%5B%5D,%22precision%22%3A%22exact%22%7D%5D&g=articles&p=1&o=-relevance

<img width="1161" alt="Screenshot 2020-03-19 at 12 17 11" src="https://user-images.githubusercontent.com/32094266/77062133-995d3c00-69db-11ea-9ad1-9e25c11d1e6c.png">

**Comment by theorm** [comment]
I think this has been fixed today.
