### ISSUE TITLE
date range on search results: difficulty to type date

### ISSUE THREAD

**Issue by Bunoute** [impresso/impresso-frontend#813]
when I try to manually set the date, as soon as I start to type, it jumps back at the end of the date box, and I need to reselect all and start again to type

**Comment by danieleguido** [comment]
Hi, I had already fixed this, strange. I’ll have a look ASAP

**Comment by danieleguido** [comment]
yep, the mechanism wasn't there. I used to check whether the date was valid before sending the event that the date had been changed. Weird.
