### ISSUE TITLE
adding word embeddings in search box does not work

### ISSUE THREAD

**Issue by Bunoute** [impresso/impresso-frontend#818]
I tried to select a few words from the "find similar"... but there was no effect...
I tried Europe and add européen, europes, furope

**Comment by Bunoute** [comment]
I tried then to add them outside from the search box, from the "find similar words" box, below. and same result: it loads forever...
https://dev.impresso-project.ch/app/search?f=%5B%7B%22type%22%3A%22hasTextContents%22%7D,%7B%22type%22%3A%22daterange%22,%22q%22%3A%5B%221900-01-01T00%3A00%3A00Z%20TO%201944-12-31T23%3A59%3A59Z%22%5D,%22op%22%3A%22OR%22%7D,%7B%22type%22%3A%22string%22,%22op%22%3A%22OR%22,%22q%22%3A%5B%22europe%22%5D,%22precision%22%3A%22exact%22%7D,%7B%22type%22%3A%22string%22,%22op%22%3A%22OR%22,%22q%22%3A%5B%5D,%22precision%22%3A%22exact%22%7D%5D&g=articles&p=1&o=-relevance

**Comment by danieleguido** [comment]
Hi @Bunoute this should be fixed now, it was related to the wrong behaviour in #820.
What worries me is the empty string filter, how did you get that in the first place?

**Comment by theorm** [comment]
I also confirm that in the recent version the embeddings work. However I am also puzzled how @Bunoute managed to add an empty string to the search 😕

**Comment by theorm** [comment]
@Bunoute if you can confirm that embeddings work in preproduction, we will close this issue.

**Comment by Bunoute** [comment]
all works well! I'll rephrase the FAQ accordingly, great work, so many thanks :)

**Comment by Bunoute** [comment]
If I remember correctly, the empty string is a topic that was selected in the graph, it worked as a filter but did not appear ...

**Comment by theorm** [comment]
> If I remember correctly, the empty string is a topic that was selected in the graph, it worked as a filter but did not appear ...

@Bunoute  Would you be able to try to reproduce it and if you can, create another issue? No rush.
