### ISSUE TITLE
dates mismatch in date filter, 1 day off

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#819]
<img width="198" alt="grafik" src="https://user-images.githubusercontent.com/4408050/78377069-703dcd80-75cf-11ea-8d08-2e6e109bbe5d.png">

I entered 30.10 and it displays 31.10.

https://impresso-project.ch/app/search?f=%5B%7B%22type%22%3A%22hasTextContents%22%7D,%7B%22type%22%3A%22language%22,%22q%22%3A%5B%22de%22%5D,%22op%22%3A%22OR%22%7D,%7B%22type%22%3A%22country%22,%22q%22%3A%5B%22CH%22%5D,%22op%22%3A%22OR%22%7D,%7B%22type%22%3A%22string%22,%22q%22%3A%22arnheim%22,%22precision%22%3A%22exact%22%7D,%7B%22type%22%3A%22daterange%22,%22q%22%3A%5B%221944-09-08T00%3A00%3A00Z%20TO%201944-10-30T23%3A59%3A59Z%22%5D,%22op%22%3A%22OR%22%7D%5D&g=articles&p=1&o=-relevance

**Comment by theorm** [comment]
This has been fixed in https://github.com/impresso/impresso-frontend/pull/851 and is available on preprod. Can you test please?
