### ISSUE TITLE
searchquery is not propagated from the homePage

### ISSUE THREAD

**Issue by danieleguido** [impresso/impresso-frontend#834]
Steps to reproduce:

1. open a new incognito browser window
2. use the autocomplete on the left to search for "einstein" 
3. this produces a correct sq that is pushed to the search page.
4. The sq is *not propagated* to the other pages, as it should.

Apparently the search query hash has not been set: if we call the function to save the searchQuery to the localStorage we can solve the issue.

**Comment by theorm** [comment]
@danieleguido I just followed your instructions and it worked. Is it because we changed something that fixed the bug in the last two weeks?
