### ISSUE TITLE
use the old f filter to create the currentSearchQuery hash

### ISSUE THREAD

**Issue by danieleguido** [impresso/impresso-frontend#835]
All the links from our feedbacks / tests uses the f parameter instaead of the new buffered one.
We can adapt the queryParams module to handle that? E.g; if there is a f params, we return the relative search query?

**Comment by theorm** [comment]
The `f` parameter is only used on the `SearchPage` (and might be `SearchImagePage` too). One is to write a script that takes an old url and converts it to a new style url. Another one is to add this conversion in the `SearchPage`. I would avoid adding it to the mapping in `queryParams` to keep it simple.
