### ISSUE TITLE
LUXWORT- unable to load TileSource

### ISSUE THREAD

**Issue by Bunoute** [impresso/impresso-frontend#837]
via TAWK: 
facsimile not visible...
https://impresso-project.ch/app/issue/luxwort-1936-04-22-a/page/luxwort-1936-04-22-a-p0013/article/luxwort-1936-04-22-a-i0075

**Comment by danieleguido** [comment]
@mromanello any thoughts on this? It looks like requests are now going to  https://iiif1.eluxemburgensia.lu and nothing appears.

**Comment by mromanello** [comment]
the strange thing is that even on dev (not touched by the patch of IIIF links) the images don't display: https://dev.impresso-project.ch/app/issue/luxwort-1936-04-22-a/page/luxwort-1936-04-22-a-p0013/article/luxwort-1936-04-22-a-i0075

**Comment by mromanello** [comment]
It rather seems an ARK resolution issue on the BNL side

<img width="685" alt="Screen Shot 2020-04-28 at 11 31 09" src="https://user-images.githubusercontent.com/310693/80471529-d2c28900-8943-11ea-9219-45fade141f3d.png">
