### ISSUE TITLE
bootstrap checkbox broken style

### ISSUE THREAD

**Issue by theorm** [impresso/impresso-frontend#841]
There is a problem with rendering of the switch checkbox in Impresso.
According to the doco, this is how it should look like: https://bootstrap-vue.org/docs/components/form-checkbox#switch-style-checkboxes

But in Impresso it looks like this:
<img width="329" alt="Screen Shot 2020-04-24 at 11 01 03" src="https://user-images.githubusercontent.com/89853/80221552-bd98e200-8645-11ea-8cd9-d74ad00dc2c0.png">

I traced it down to some style manipulation in impresso-theme - bootpresso.css
As I understand changes to generic bootstrap label classes override specific changes to checkbox switch style labels. We are going to use this particular checkbox style so it would be good to have it fixed.

**Comment by PaulSchroeder** [comment]
I have updated bootpresso with the current version of bootstrap, adding switches among others.
You have to fetch the new `impresso-theme/dist/css/bootpresso.css`

**Comment by PaulSchroeder** [comment]
I used it like this
```
<b-form-checkbox v-model="selected" name="check-button" switch>
  Switch Checkbox <b>(Checked: {{ selected }})</b>
</b-form-checkbox>
```

**Comment by PaulSchroeder** [comment]
<img width="399" alt="Screenshot 2020-04-28 at 16 41 32" src="https://user-images.githubusercontent.com/32929425/80500970-29918800-896f-11ea-81cd-41ed1d18f7a1.png">
<img width="398" alt="Screenshot 2020-04-28 at 16 41 23" src="https://user-images.githubusercontent.com/32929425/80500988-2dbda580-896f-11ea-92c4-a1119d82feff.png">

**Comment by theorm** [comment]
Hi Paul. That's great, thank you. I can confirm it is working.
Now we have a similar problem with a slider (`b-form-input` type=`range`). Can you have a look into it as well?

<img width="520" alt="Screen Shot 2020-04-30 at 16 06 58" src="https://user-images.githubusercontent.com/89853/80720145-cc2b4180-8afc-11ea-97b9-2d87c77c5647.png">

**Comment by PaulSchroeder** [comment]
Hi Roman, great ! I noticed a visibility problem on the search page, this applies to all types checkboxes ...

<img width="159" alt="Screenshot 2020-04-30 at 19 24 09" src="https://user-images.githubusercontent.com/32929425/80740302-2be31600-8b18-11ea-823f-a936560fca4a.png">

Will amend like this :
<img width="140" alt="Screenshot 2020-04-30 at 19 31 03" src="https://user-images.githubusercontent.com/32929425/80740944-23d7a600-8b19-11ea-9c3b-c416a4480a96.png">

**Comment by danieleguido** [comment]
Hi @PaulSchroeder, Probably related to your latest changes on *impresso-theme*, this happens onhover to dropdown items:
![Screen-Recording-2020-05-03-at-15 46 17](https://user-images.githubusercontent.com/1181642/80915938-b2d10200-8d55-11ea-9802-8c88e362a296.gif)

**Comment by danieleguido** [comment]
Thanks it works in pre-prod! closing
