### ISSUE TITLE
Monitor component for Text reuse items doesn't link to text reuse cluster page

### ISSUE THREAD

**Issue by danieleguido** [impresso/impresso-frontend#854]
The text reuse links are available in the collection recommender panel 
<img width="671" alt="Screenshot 2020-05-05 at 10 38 34" src="https://user-images.githubusercontent.com/1181642/81048467-b337dd00-8ebc-11ea-853d-e7ec9805233e.png">

<img width="655" alt="Screenshot 2020-05-05 at 10 41 26" src="https://user-images.githubusercontent.com/1181642/81048656-0447d100-8ebd-11ea-9ae9-ad9f528ac6a0.png">

**Comment by theorm** [comment]
Fixed in https://github.com/impresso/impresso-frontend/pull/865
