### ISSUE TITLE
compare page: missing labels for topics and collections

### ISSUE THREAD

**Issue by danieleguido** [impresso/impresso-frontend#855]
Topics are undefined:
<img width="583" alt="Screenshot 2020-05-05 at 11 09 38" src="https://user-images.githubusercontent.com/1181642/81050812-f300c380-8ec0-11ea-9df3-9934fbef936b.png">
https://dev.impresso-project.ch/app/compare?left=CgIYAgoOEAIYByABKgZhcm5oZW0KTggCEAIYEioWdG0tZnItYWxsLXYyLjBfdHA1MF9mcioWdG0tZnItYWxsLXYyLjBfdHA3NV9mcioWdG0tZnItYWxsLXYyLjBfdHA2Ml9mcgoeCAIQAhgSKhZ0bS1kZS1hbGwtdjIuMF90cDE3X2Rl

**Comment by theorm** [comment]
This has been fixed.
