### ISSUE TITLE
integrate FAQ info on different pages

### ISSUE THREAD

**Issue by danieleguido** [impresso/impresso-frontend#866]
- [x] ngrams view: added `what-are-ngram` and `how-search-ngrams-work-with-search-filters`
- [x] i&c view: add in middle column
- [x] text reuse: add info button next to "clusters" label
- [x] issue page: add text reuse info button nex to passages graphics

**Comment by Bunoute** [comment]
"id": "what-are-ngram"

**Comment by Bunoute** [comment]
and for the text reuse:   "id": "text-reuse"

**Comment by danieleguido** [comment]
@Bunoute can you confirm is this complete?

**Comment by Bunoute** [comment]
looks fine ! thanks :)

**Comment by Bunoute** [comment]
maybe a minor, late, suggestion: for the topic graph: the info button could connect to "id": "topic-graph" rather than "id": "why-topic" ?
