### ISSUE TITLE
list of images: fix vertial images, fix ordering of elements

### ISSUE THREAD

**Issue by danieleguido** [impresso/impresso-frontend#881]
the use of columns is wrong in this case, as the elements need to be sorted horizontally... and columns rearrange items vertically.

**Comment by PaulSchroeder** [comment]
https://github.com/impresso/impresso-frontend/pull/883

**Comment by danieleguido** [comment]
elegant solution @PaulSchroeder if we want to do something more we would go to https://www.npmjs.com/package/vue-masonry

**Comment by PaulSchroeder** [comment]
hey yes… masonry is cool, but I think it would be really over engineering to use it here :)
