### ISSUE TITLE
impresso challenges link broken

### ISSUE THREAD

**Issue by Bunoute** [impresso/impresso-frontend#882]
the link on the app's homepage does not open this file: https://github.com/impresso/impresso-frontend/blob/develop/src/assets/impresso-challenges-1.2.3.pdf

**Comment by danieleguido** [comment]
(still to be changed with https://impresso-project.ch/assets/impresso-challenges-1.2.3.pdf as @theorm pointed out in a pm)

**Comment by danieleguido** [comment]
fixed in pre-prod
