### ISSUE TITLE
unable to load tile source 

### ISSUE THREAD

**Issue by Bunoute** [impresso/impresso-frontend#887]
here: https://impresso-project.ch/app/search?sq=Ch4IARACGBIqFnRtLWZyLWFsbC12Mi4wX3RwNjlfZnIKHggBEAIYEioWdG0tZnItYWxsLXYyLjBfdHA1NV9mcgoeCAEQAhgSKhZ0bS1mci1hbGwtdjIuMF90cDg3X2ZyCh4IARACGBIqFnRtLWZyLWFsbC12Mi4wX3RwOTdfZnIKCBACGA0qAmFy&p=4

this happened: 
<img width="728" alt="Screenshot 2020-05-12 at 16 38 30" src="https://user-images.githubusercontent.com/32094266/81705379-46e64c00-946f-11ea-8a3c-92af9c9260b0.png">

**Comment by danieleguido** [comment]
HI @Bunoute I cannot reproduce it, probably it was a temporary issue

**Comment by danieleguido** [comment]
Closed as duplicate, I've moved the not working url to #943 (we can collect all not working image uris on that issue)
