### ISSUE TITLE
when selecting topics from the topic graph, the labels are lost on search page

### ISSUE THREAD

**Issue by Bunoute** [impresso/impresso-frontend#888]
again, doing this query: https://impresso-project.ch/app/search?sq=Ch4IARACGBIqFnRtLWZyLWFsbC12Mi4wX3RwNjlfZnIKHggBEAIYEioWdG0tZnItYWxsLXYyLjBfdHA1NV9mcgoeCAEQAhgSKhZ0bS1mci1hbGwtdjIuMF90cDg3X2ZyCh4IARACGBIqFnRtLWZyLWFsbC12Mi4wX3RwOTdfZnIKCBACGA0qAmFy&p=4

first I selected the topics on the topic graph, added them as search filters, which works great ( :) ), I then went to the search page and in the human readable summary (also when I tried to create a collection out of the search results), the labels of the topics where lost, but not in the search pills:

<img width="1124" alt="Screenshot 2020-05-12 at 16 43 55" src="https://user-images.githubusercontent.com/32094266/81705898-d1c74680-946f-11ea-9325-d415798efc09.png">

**Comment by danieleguido** [comment]
(ready to be deployed in the upcoming release,see pre prod 
 https://dev.impresso-project.ch/app/search?sq=Ch4IARACGBIqFnRtLWZyLWFsbC12Mi4wX3RwNjlfZnIKHggBEAIYEioWdG0tZnItYWxsLXYyLjBfdHA1NV9mcgoeCAEQAhgSKhZ0bS1mci1hbGwtdjIuMF90cDk3X2ZyCggQAhgNKgJhcg%3D%3D&p=1)
