### ISSUE TITLE
integrate tags input component to save user labels

### ISSUE THREAD

**Issue by danieleguido** [impresso/impresso-frontend#90]
Hi I found this component in vue, it has basic autocomplete functionalities as well. What do you think?
http://www.vue-tags-input.com/#/

**Comment by tvanbeek** [comment]
Yeah pretty cool. To replace the current autocomplete? Or just for the labels/tags component so users can search and add?

**Comment by danieleguido** [comment]
It will be nice to have an alternative version of the search autocomplete, but for the moment I'd like to have it for the personal tags/labels only ;)

For the collections IMO we should still keep the github approach:
<img width="328" alt="screenshot 2018-11-02 at 09 59 30" src="https://user-images.githubusercontent.com/1181642/47904892-0c691f80-de86-11e8-8e22-7e8ec41fcb2d.png">
