### ISSUE TITLE
ngram viewer: Adding search for semantically similar words to ngram viewer 

### ISSUE THREAD

**Issue by simon-clematide** [impresso/impresso-frontend#904]
While reading our proposal again, I notices that we planned the suggestion of similar words for the ngram viewer. I think this is needed to fulfill at least a bit of the promised improved ngram functionality (being able to filter along all facets is another one).
Could we just have an slightly modified instance of the "add similar word dialog box" there as in the normal search?

![image](https://user-images.githubusercontent.com/3041168/83729955-b1db0b00-a648-11ea-96a2-0a92cbbe58e0.png)

**Comment by danieleguido** [comment]
yes that's a good idea, it shouldn't be that hard
