### ISSUE TITLE
newspaper page says it shows front pages, but shows other pages

### ISSUE THREAD

**Issue by simon-clematide** [impresso/impresso-frontend#911]
E.g. https://impresso-project.ch/app/newspapers/NTS shows not only first pages and similar for other newspapers, e.g. https://impresso-project.ch/app/newspapers/NZG
![image](https://user-images.githubusercontent.com/3041168/84565127-5b1bb280-ad67-11ea-8246-9dccbc395e70.png)

**Comment by simon-clematide** [comment]
All frontpages should actually be recognizable by their page number 0001

**Comment by danieleguido** [comment]
Fixed in [middle-layer,](https://github.com/impresso/impresso-middle-layer/commit/ba2816b4003c4ee3097e701691490e341c37d708) now available on current dev https://dev.impresso-project.ch/app/newspapers/NZG
