### ISSUE TITLE
ngram viewer: Multi-word search with SOLR

### ISSUE THREAD

**Issue by simon-clematide** [impresso/impresso-frontend#915]
@theorm Can we use the PhraseQuery of Solr "foo bar"~0  (actually the `~0` is the default) to allow arbitrary n-grams to be searched? I think this would be straightforward (see #891).
I know that stopwords and punctuation tokens between the queried words will be ignored but I think this is acceptable. 

- With regard to the query language/user interface: Should we go more in the direction of https://books.google.com/ngrams/info ? Meaning, e.g. space for separating multiwords? Comma for several ngrams? 

-  Maybe we could add an expert information on what was actually queried (in the spirit of tool transparency) by providing the query debug information?  E.g. a query "aggressiven Ländern" within German content actually searches for everything that was normalized to "land" in German articles: `https://solrdev.dhlab.epfl.ch/solr/impresso_dev/select?q=content_txt_de:"aggressiven Ländern"&debug=query`

```
 "debug":{
    "rawquerystring":"content_txt_de:\"aggressiven Ländern\"",
    "querystring":"content_txt_de:\"aggressiven Ländern\"",
    "parsedquery":"PhraseQuery(content_txt_de:\"aggressiv land\")",
    "parsedquery_toString":"content_txt_de:\"aggressiv land\"",
    "QParser":"LuceneQParser"}}
```

**Comment by theorm** [comment]
Hi Simon,

I'll get back to this when I have more time. Just one comment.

`Meaning, e.g. space for separating multiwords? Comma for several ngrams?` - we cannot do ngrams with current Solr setup, only unigrams. We talked about potential ways to do multigrams and I don't think we found a solution for this.
