### ISSUE TITLE
ngram viewer: article counts not shown with multiple unigrams

### ISSUE THREAD

**Issue by simon-clematide** [impresso/impresso-frontend#917]
The article counts are somehow suppressed for all but the last unigram.
![image](https://user-images.githubusercontent.com/3041168/84752186-b810a600-afbd-11ea-9ca4-905456631142.png)

**Comment by theorm** [comment]
@danieleguido looks like the label is not rendered properly. The `in <count>` part should only appear at the end, shouldn't it?
