### ISSUE TITLE
Viewer - not displaying facsimile for LUX WORT, and others

### ISSUE THREAD

**Issue by Bunoute** [impresso/impresso-frontend#943]
https://dev.impresso-project.ch/app/issue/buergerbeamten-1912-04-20-a/page/buergerbeamten-1912-04-20-a-p0002/article/buergerbeamten-1912-04-20-a-i0004

https://dev.impresso-project.ch/app/issue/obermosel-1947-05-05-a/page/obermosel-1947-05-05-a-p0005/article/obermosel-1947-05-05-a-i0031

https://dev.impresso-project.ch/app/issue/indeplux-1912-04-27-a/page/indeplux-1912-04-27-a-p0003/article/indeplux-1912-04-27-a-i0002

https://impresso-project.ch/app/issue/luxwort-1912-04-22-a/page/luxwort-1912-04-22-a-p0002/article/luxwort-1912-04-22-a-i0008

**Comment by danieleguido** [comment]
I remove the label bug as it was mainly related to a IIIF issue on Lux side.

**Comment by danieleguido** [comment]
Also check https://impresso-project.ch/app/search?sq=Ch4IARACGBIqFnRtLWZyLWFsbC12Mi4wX3RwNjlfZnIKHggBEAIYEioWdG0tZnItYWxsLXYyLjBfdHA1NV9mcgoeCAEQAhgSKhZ0bS1mci1hbGwtdjIuMF90cDg3X2ZyCh4IARACGBIqFnRtLWZyLWFsbC12Mi4wX3RwOTdfZnIKCBACGA0qAmFy&p=4
