### ISSUE TITLE
homepage: check data rundown (or load from stats)

### ISSUE THREAD

**Issue by danieleguido** [impresso/impresso-frontend#968]

**Comment by PaulSchroeder** [comment]
on homepage | found
------------ | -------------
76 newspapers collected | still correct
600,919 issues | can't find stat
5,429,656 pages scanned | can't find stat
47,798,468 content items identified | can't find stat
- [ ] 3,462,799 images | found only 2,276,555 in image viewer
12,493,358,703 words | can't find stat

**Comment by PaulSchroeder** [comment]
I noticed that in [this post from January](https://impresso-project.ch/news/2020/01/23/state-corpus-january2020.html), the number of content items and issues is slightly higher. 

@mromanello @e-maud 
are these figures still up-to-date?
is there a way I can retrieve the stats in real-time?

**Comment by mromanello** [comment]
Hi @PaulSchroeder, (cc @danieleguido and @theorm)

Unfortunately there is not realtime way of fetching this, **but** with @e-maud and @simon-clematide we are currently working on a GitHub -based system to store JSON manifests with information about data components of each release, see https://github.com/impresso/impresso-data-release/tree/documenting-release-v01

The idea is that you'll be able to get all the stats above directly from the main `manifest.json` file hosted in that repo. Also you can trust the stats you'll find there and display them directly in the interface. Computing them is quite resource intensive (the use EPFL's kubernetes cluster to progess GBs of JSON data). 

Also, the manifest file will contain a **data release version** that you should display in the "Which version of Impresso am I using" section of the FAQ.
