### ISSUE TITLE
marginalia in article viewer

### ISSUE THREAD

**Issue by danieleguido** [impresso/impresso-frontend#973]
would it be possible to make the NEs clickable? To highlight the person/location mentioned on the page on the facsimile view?

**Comment by PaulSchroeder** [comment]
We don't have an ID of the entity, we do have a relative entity count though, e.g. **location-xx**
`<span data-id="location-0" class="entity location">Milan</span>`

I will try to link them to the article entity table

**Comment by PaulSchroeder** [comment]
I found this in **articleAnnotations.js** 
  // NOTE: "location" and "person" entities do not correspond to the mentions offsets
  // in another field. This means that some of the entities mentioned have not
  // been disambiguated and we cannot rely on mention -> entity match. Until this
  // is fixed we use mentions indexes as IDs.
  // const locationIds = namedEntitiesToListOfIds(response.locations || []);
  // const personIds = namedEntitiesToListOfIds(response.persons || []);`

so we can't rely on mention -> entity match.
is that still correct @daniele @theorm  ?
