### ISSUE TITLE
I&C: add date filter in column B?

### ISSUE THREAD

**Issue by Bunoute** [impresso/impresso-frontend#985]
is it planned to be able to add date filter to the B column (and column A if the query is not imported from the search page)

currently, we can select the years in the refine button, and they are ordered by frequency. will it stay that way?

**Comment by danieleguido** [comment]
Hi @Bunoute we have a timeline component integrated a s a daterange filter for text-reuse. I suggest we remove the "years" and we use that component, probably something for @PaulSchroeder ?

<img width="566" alt="Screenshot 2020-08-26 at 10 42 28" src="https://user-images.githubusercontent.com/1181642/91281874-ddbde680-e788-11ea-8578-870c005960f9.png">

**Comment by PaulSchroeder** [comment]
yo, I'll add that.

**Comment by theorm** [comment]
@PaulSchroeder don't worry, I'm getting on it today.

**Comment by theorm** [comment]
Hi @Bunoute , the change is on dev. Can you verify it when you have a moment? Thank you

**Comment by Bunoute** [comment]
hi @theorm, thanks for this! the filter is available in refine, thanks! 
it seems however that it does not impact the frequency below... or should I just wait a bit?

https://dev.impresso-project.ch/app/compare?left=CgIYAgqOAhACGAcgASoGZXVyb3BlKgdldXJvcGVzKglldXJvcMOpZW4qBmV1cm9wYyoGZnVyb3BlKgZldXRvcGUqBmV1cm9uZSoKZXVyb3DDqWVucyoGZXVpb3BlKgdyb3DDqWVuKgVww6llbioIcm9ww6llbnMqC2V1cm9ww6llbm5lKgZww6llbnMqBmV1cm9vZSoHcMOpZW5uZSoGZXVyb3BpKgZldXJjcGUqBmV1cnBwZSoHZXVyb3BhcyoNZXVyb3DDpGlzY2hlbioMZXVyb3DDpGlzY2hlKgZrdXJvcGEqBmJ1cm9wYSoIcMOkaXNjaGUqBHJvcGEqCXDDpGlzY2hlbioFdXJvcGEqBmVucm9wYQoIEAEYDCoCZnIKCBABGBYqAkNICg0QARgHIAEqBWNyaXNlCgoIAhABGBYqAkxVCjQIARACGAoqLDE5MjAtMTItMTBUMDA6MDA6MDBaIFRPIDE5NDQtMDItMjFUMjM6NTk6NTlaCiIQAhgJKgNKREcqA0dETCoDRVhQKgNJTVAqA0xFUyoDTENF&right=CgIYAgqOAhACGAcgASoGZXVyb3BlKgdldXJvcGVzKglldXJvcMOpZW4qBmV1cm9wYyoGZnVyb3BlKgZldXRvcGUqBmV1cm9uZSoKZXVyb3DDqWVucyoGZXVpb3BlKgdyb3DDqWVuKgVww6llbioIcm9ww6llbnMqC2V1cm9ww6llbm5lKgZww6llbnMqBmV1cm9vZSoHcMOpZW5uZSoGZXVyb3BpKgZldXJjcGUqBmV1cnBwZSoHZXVyb3BhcyoNZXVyb3DDpGlzY2hlbioMZXVyb3DDpGlzY2hlKgZrdXJvcGEqBmJ1cm9wYSoIcMOkaXNjaGUqBHJvcGEqCXDDpGlzY2hlbioFdXJvcGEqBmVucm9wYQoIEAEYDCoCZnIKCBABGBYqAkNICg0QARgHIAEqBWNyaXNlCgoIAhABGBYqAkxVCiIQAhgJKgNKREcqA0dETCoDRVhQKgNJTVAqA0xFUyoDTENFCjQIARACGAoqLDE5MjQtMDItMTRUMDA6MDA6MDBaIFRPIDIwMDYtMDgtMjFUMjM6NTk6NTla

<img width="1223" alt="Screenshot 2020-08-27 at 16 08 46" src="https://user-images.githubusercontent.com/32094266/91453092-a120e680-e87f-11ea-9689-9c8358d84ca8.png">

**Comment by theorm** [comment]
Hi @Bunoute , it does impact frequency but it is not calculated correctly because of another bug that you just uncovered which was due to multiple time periods not being joined with the correct operator. It is now fixed and if you open the link above you'll see a different frequency in the intersection.

In fact I just noticed another bug not related to I&C. If you click the "Open in search page" button, you'll see a couple of errors popping up. I'll create a separate issue for this. But please let me know if you consider the frequencies problem fixed and I'll close this issue then. Thank you.

**Comment by Bunoute** [comment]
hi @theorm, it seems to be working, thanks!
