### ISSUE TITLE
ngram viewer: Deleting a word from the unigram list leads to an error shown in the interface

### ISSUE THREAD

**Issue by simon-clematide** [impresso/impresso-frontend#991]
When clicking on a unigram in the input box to remove a word, a yellow error bar appears.

![image](https://user-images.githubusercontent.com/3041168/91722637-d50b4d00-eb9a-11ea-98f1-0b1255051a07.png)

**Comment by theorm** [comment]
I tried to reproduce it and I managed to get the error the first time. Then I reloaded the page (with Ctrl-Shift-R) and the error never came back no matter what kind of combinations of unigrams I tried. I suspect it's either a concurrency related error or some old javascript files were cached that were renewed after I refreshed the page.

**Comment by simon-clematide** [comment]
I tried it as well after the reload and could not reproduce it as well. Case closed:-) Thanks for checking it.
