### ISSUE TITLE
bugs when creating collections - a few examples

### ISSUE THREAD

**Issue by Bunoute** [impresso/impresso-frontend#993]
it seems not all information/articles are properly saved or displayed in the collections.

Here is an example from one user (the query underlying that collection has hits until 1914)
![IMG_0288](https://user-images.githubusercontent.com/32094266/91840630-4ad1f000-ec51-11ea-9792-800f0fff0deb.jpg)

and a few of mine, where there is always the same frequency line, independently of the collection
<img width="1181" alt="Screenshot 2020-09-01 at 14 24 42" src="https://user-images.githubusercontent.com/32094266/91852853-ae641980-ec61-11ea-9739-32b00181bb9e.png">

link to the collection: https://impresso-project.ch/app/collections/local-eb-tPj07s_9

<img width="1181" alt="Screenshot 2020-09-01 at 14 24 19" src="https://user-images.githubusercontent.com/32094266/91852864-b0c67380-ec61-11ea-9fb9-8959d71735f0.png">

link to the collection: https://impresso-project.ch/app/collections/local-eb-3scE0Cfr

**Comment by PaulSchroeder** [comment]
Thanks for pointing that out. 
There is a major bug with **create a new collection from search results** it seems to ignore the current search results,
I always end up with 10,000 items, even if I have only 10 items in my search results.

**Comment by mromanello** [comment]
yes, I've just experienced this bug too, (tested with both prod and pre-prod interfaces). It's quite a major one...

**Comment by theorm** [comment]
A few people reported in Slack that this has been fixed. Feel free to reopen if it's not the case.
