### ISSUE TITLE
text reuse page: add human readable summary? search pill?

### ISSUE THREAD

**Issue by Bunoute** [impresso/impresso-frontend#999]
when searching for clusters containing a given word, we are not sure that the query has been conducted, what are the active filters... 
contrary to the search page, we browse the result list on the left side, which could be a bit confusing: need to add some explanation in the FAQ but maybe a human readable summary appearing above the result list could help indicate that.
would it be complicated to add several keywords? to search for "crise" AND "europe", for instance?

**Comment by Bunoute** [comment]
would it be possible also to "translate":
- the numbers of days in months/years for the cluster span?
- add % for the lexical overlap?
- what is the unit of the cluster size? characters/words?

**Comment by PaulSchroeder** [comment]
> would it be possible also to "translate":
> 
> * the numbers of days in months/years for the cluster span?
> * add % for the lexical overlap?

where is that missing? 

> * what is the unit of the cluster size? characters/words?

I think the unit is slightly more esoteric than that 🤓

**Comment by danieleguido** [comment]
Hi @Bunoute cluster size = number of text reuse passages in the cluster. Translation is possible of course and pretty straightforward to do, and lexical overlapp labels can be enriched with %

**Comment by danieleguido** [comment]
fixed in current develop.
<img width="1124" alt="Screenshot 2024-03-18 at 15 10 29" src="https://github.com/impresso/impresso-frontend/assets/1181642/64c853cc-779d-4562-980b-3f0cb9f06d48">
